import type { Requirement } from './requirements';

export const VERIFIED_PRESETS: Requirement[] = [
  {
    id: 'us-passport-photo',
    country: 'United States',
    organization: 'Department of State',
    portal: 'travel.state.gov',
    documentType: 'Passport Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: null,
      maxBytes: 245760, // 240 KB
      minWidth: 600,
      maxWidth: 1200,
      minHeight: 600,
      maxHeight: 1200,
      widthMm: 51,
      heightMm: 51,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'plain white or off-white',
      allowBackgroundEdit: false,
      headSizePercent: { min: 50, max: 69 },
      maxPages: 1,
      notes: 'Photo must be 2×2 inches (51×51 mm), 600×600 to 1200×1200 pixels, JPEG format, under 240 KB, on a plain white or off-white background.',
    },
    sourceUrl: 'https://travel.state.gov/content/travel/en/passports/how-apply/photos.html',
    lastVerified: '2026-09-28',
    verifiedBy: 'Official Department of State Photo Guidelines',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'us-visa-photo',
    country: 'United States',
    organization: 'Department of State Consular Affairs',
    portal: 'ceac.state.gov / travel.state.gov',
    documentType: 'Visa Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: null,
      maxBytes: 245760, // 240 KB
      minWidth: 600,
      maxWidth: 1200,
      minHeight: 600,
      maxHeight: 1200,
      widthMm: 51,
      heightMm: 51,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'plain white or off-white',
      allowBackgroundEdit: false,
      headSizePercent: { min: 50, max: 69 },
      maxPages: 1,
      notes: 'Photo for US visa application (DS-160) must be square (2×2 inches, min 600×600 px), JPEG format, under 240 KB.',
    },
    sourceUrl: 'https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html',
    lastVerified: '2026-09-28',
    verifiedBy: 'Official US Visa Photo Requirements',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'uk-passport-photo',
    country: 'United Kingdom',
    organization: 'HM Passport Office',
    portal: 'gov.uk',
    documentType: 'Passport Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 51200, // 50 KB
      maxBytes: 10485760, // 10 MB
      minWidth: 600,
      maxWidth: null,
      minHeight: 750,
      maxHeight: null,
      widthMm: 35,
      heightMm: 45,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'plain light grey or plain cream',
      allowBackgroundEdit: false,
      headSizePercent: { min: 64, max: 75 },
      maxPages: 1,
      notes: 'Digital passport photo must be at least 600 pixels wide and 750 pixels tall, between 50 KB and 10 MB, on a plain light grey or cream background.',
    },
    sourceUrl: 'https://www.gov.uk/photos-for-passports',
    lastVerified: '2026-09-28',
    verifiedBy: 'Official GOV.UK Passport Guidance',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'schengen-visa-photo',
    country: 'European Union (Schengen)',
    organization: 'European Commission',
    portal: 'visa.vfsglobal.com / consulates',
    documentType: 'Schengen Visa Photo',
    requirements: {
      formats: ['image/jpeg', 'image/png'],
      minBytes: 20480, // 20 KB
      maxBytes: 2097152, // 2 MB
      minWidth: 600,
      maxWidth: 1200,
      minHeight: 800,
      maxHeight: 1600,
      widthMm: 35,
      heightMm: 45,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'uniform light grey or white',
      allowBackgroundEdit: false,
      headSizePercent: { min: 70, max: 80 },
      maxPages: 1,
      notes: 'Schengen visa photo must measure 35×45 mm, head height between 32 and 36 mm (70–80% of image height), light uniform background with no patterns.',
    },
    sourceUrl: 'https://home-affairs.ec.europa.eu/policies/schengen-borders-and-visa/visa-policy_en',
    lastVerified: '2026-09-28',
    verifiedBy: 'Schengen Visa Specifications (ICAO Doc 9303 standard)',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'canada-visa-photo',
    country: 'Canada',
    organization: 'Immigration, Refugees and Citizenship Canada (IRCC)',
    portal: 'canada.ca',
    documentType: 'Visa / Study Permit Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 61440, // 60 KB
      maxBytes: 245760, // 240 KB
      minWidth: 420,
      maxWidth: null,
      minHeight: 540,
      maxHeight: null,
      widthMm: 35,
      heightMm: 45,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'plain white or light-coloured',
      allowBackgroundEdit: false,
      headSizePercent: { min: 68, max: 80 },
      maxPages: 1,
      notes: 'Canadian visa photograph frame must measure at least 35×45 mm with min 420×540 pixels. File size must be between 60 KB and 240 KB.',
    },
    sourceUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/application/application-forms-guides/temporary-resident-visa-application-photograph-specifications.html',
    lastVerified: '2026-09-28',
    verifiedBy: 'IRCC Canada Official Photograph Specifications',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'australia-passport-photo',
    country: 'Australia',
    organization: 'Australian Passport Office',
    portal: 'passports.gov.au',
    documentType: 'Passport Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: null,
      maxBytes: 5242880, // 5 MB
      minWidth: 820,
      maxWidth: null,
      minHeight: 1050,
      maxHeight: null,
      widthMm: 35,
      heightMm: 45,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'plain white or light grey',
      allowBackgroundEdit: false,
      headSizePercent: { min: 71, max: 80 },
      maxPages: 1,
      notes: 'Australian passport photos must be 35–40 mm wide and 45–50 mm high. Online photos must be min 820×1050 px, under 5 MB, on a plain white or light grey background.',
    },
    sourceUrl: 'https://www.passports.gov.au/files/passport-photo-guidelines',
    lastVerified: '2026-09-28',
    verifiedBy: 'Australian Passport Office Guidelines',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'india-passport-photo',
    country: 'India',
    organization: 'Ministry of External Affairs (Passport Seva)',
    portal: 'passportindia.gov.in',
    documentType: 'Passport & OCI Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 20480, // 20 KB
      maxBytes: 307200, // 300 KB
      minWidth: 350,
      maxWidth: 1000,
      minHeight: 350,
      maxHeight: 1000,
      widthMm: 51,
      heightMm: 51,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'plain white',
      allowBackgroundEdit: false,
      headSizePercent: { min: 65, max: 75 },
      maxPages: 1,
      notes: 'Indian Passport / OCI photo must be square (2×2 inches / 51×51 mm), 350×350 to 1000×1000 px, file size between 20 KB and 300 KB on a pure white background.',
    },
    sourceUrl: 'https://passportindia.gov.in/AppOnlineProject/pdf/Photo_Specification.pdf',
    lastVerified: '2026-09-28',
    verifiedBy: 'Passport Seva MEA India Photo Specifications',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'china-visa-photo',
    country: 'China',
    organization: 'Department of Consular Affairs (MFA)',
    portal: 'cova.mfa.gov.cn',
    documentType: 'Visa Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 40960, // 40 KB
      maxBytes: 122880, // 120 KB
      minWidth: 354,
      maxWidth: 420,
      minHeight: 472,
      maxHeight: 560,
      widthMm: 33,
      heightMm: 48,
      minDpi: 300,
      colorMode: 'RGB color (24 bit)',
      background: 'pure white',
      allowBackgroundEdit: false,
      headSizePercent: { min: 58, max: 70 },
      maxPages: 1,
      notes: 'Chinese visa photo must measure 33×48 mm (354×472 to 420×560 pixels), file size between 40 KB and 120 KB, on a pure white background.',
    },
    sourceUrl: 'https://cova.mfa.gov.cn',
    lastVerified: '2026-09-28',
    verifiedBy: 'China Online Visa Application (COVA) Guidelines',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'japan-visa-photo',
    country: 'Japan',
    organization: 'Ministry of Foreign Affairs (MOFA)',
    portal: 'mofa.go.jp',
    documentType: 'Visa Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: null,
      maxBytes: 2097152, // 2 MB
      minWidth: 600,
      maxWidth: null,
      minHeight: 800,
      maxHeight: null,
      widthMm: 35,
      heightMm: 45,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'plain white',
      allowBackgroundEdit: false,
      headSizePercent: { min: 70, max: 80 },
      maxPages: 1,
      notes: 'Japanese visa photo must be 35×45 mm (or 45×45 mm), taken within 6 months, plain white background without shadow, under 2 MB.',
    },
    sourceUrl: 'https://www.mofa.go.jp/j_info/visit/visa/index.html',
    lastVerified: '2026-09-28',
    verifiedBy: 'MOFA Japan Visa Application Guidelines',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'jee-main-photo',
    country: 'India',
    organization: 'National Testing Agency (NTA)',
    portal: 'jeemain.nta.nic.in',
    documentType: 'Exam Candidate Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 10240, // 10 KB
      maxBytes: 204800, // 200 KB
      minWidth: 200,
      maxWidth: 600,
      minHeight: 250,
      maxHeight: 800,
      widthMm: 35,
      heightMm: 45,
      minDpi: 200,
      colorMode: 'RGB color',
      background: 'white background with 80% face visible',
      allowBackgroundEdit: false,
      headSizePercent: { min: 75, max: 85 },
      maxPages: 1,
      notes: 'JEE Main candidate photograph must be between 10 KB and 200 KB in JPG/JPEG format with 80% face coverage against a white background.',
    },
    sourceUrl: 'https://jeemain.nta.nic.in/',
    lastVerified: '2026-09-28',
    verifiedBy: 'NTA JEE (Main) Information Bulletin',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'jee-main-signature',
    country: 'India',
    organization: 'National Testing Agency (NTA)',
    portal: 'jeemain.nta.nic.in',
    documentType: 'Candidate Signature',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 4096, // 4 KB
      maxBytes: 30720, // 30 KB
      minWidth: 100,
      maxWidth: 400,
      minHeight: 40,
      maxHeight: 200,
      widthMm: 35,
      heightMm: 15,
      minDpi: 200,
      colorMode: 'Black/Dark Blue ink on white paper',
      background: 'white paper',
      allowBackgroundEdit: true,
      headSizePercent: null,
      maxPages: 1,
      notes: 'JEE Main signature must be between 4 KB and 30 KB in JPG/JPEG format, approximately 3.5×1.5 cm (around 140×60 px), signed with black or blue ink on clean white paper.',
    },
    sourceUrl: 'https://jeemain.nta.nic.in/',
    lastVerified: '2026-09-28',
    verifiedBy: 'NTA JEE (Main) Information Bulletin',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'neet-photo',
    country: 'India',
    organization: 'National Testing Agency (NTA)',
    portal: 'neet.nta.online',
    documentType: 'NEET UG Candidate Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 10240, // 10 KB
      maxBytes: 204800, // 200 KB
      minWidth: 200,
      maxWidth: 600,
      minHeight: 250,
      maxHeight: 800,
      widthMm: 35,
      heightMm: 45,
      minDpi: 200,
      colorMode: 'RGB color',
      background: 'white background with 80% face coverage',
      allowBackgroundEdit: false,
      headSizePercent: { min: 75, max: 85 },
      maxPages: 1,
      notes: 'NEET UG passport photograph must be between 10 KB and 200 KB, JPG/JPEG format, on a white background showing ears.',
    },
    sourceUrl: 'https://neet.nta.online/',
    lastVerified: '2026-09-28',
    verifiedBy: 'NTA NEET UG Official Information Bulletin',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'neet-signature',
    country: 'India',
    organization: 'National Testing Agency (NTA)',
    portal: 'neet.nta.online',
    documentType: 'NEET UG Signature',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 4096, // 4 KB
      maxBytes: 30720, // 30 KB
      minWidth: 100,
      maxWidth: 400,
      minHeight: 40,
      maxHeight: 200,
      widthMm: 35,
      heightMm: 15,
      minDpi: 200,
      colorMode: 'Black ink on white paper',
      background: 'white paper',
      allowBackgroundEdit: true,
      headSizePercent: null,
      maxPages: 1,
      notes: 'NEET UG signature must be between 4 KB and 30 KB, JPG/JPEG format, signed with black pen on white paper.',
    },
    sourceUrl: 'https://neet.nta.online/',
    lastVerified: '2026-09-28',
    verifiedBy: 'NTA NEET UG Official Information Bulletin',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'gate-photo',
    country: 'India',
    organization: 'GATE Organizing Institute (IITs)',
    portal: 'gate2025.iitr.ac.in',
    documentType: 'GATE Exam Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 5120, // 5 KB
      maxBytes: 204800, // 200 KB
      minWidth: 240,
      maxWidth: 480,
      minHeight: 320,
      maxHeight: 640,
      widthMm: 35,
      heightMm: 45,
      minDpi: 200,
      colorMode: 'RGB color',
      background: 'plain white',
      allowBackgroundEdit: false,
      headSizePercent: { min: 60, max: 70 },
      maxPages: 1,
      notes: 'GATE photo must have aspect ratio 3.5:4.5 (e.g. 240×320 to 480×640 px), between 5 KB and 200 KB in JPEG format, on a white background.',
    },
    sourceUrl: 'https://gate2025.iitr.ac.in/',
    lastVerified: '2026-09-28',
    verifiedBy: 'GATE Official Application Guide',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'gate-signature',
    country: 'India',
    organization: 'GATE Organizing Institute (IITs)',
    portal: 'gate2025.iitr.ac.in',
    documentType: 'GATE Exam Signature',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 3072, // 3 KB
      maxBytes: 102400, // 100 KB
      minWidth: 280,
      maxWidth: 560,
      minHeight: 80,
      maxHeight: 160,
      widthMm: 70,
      heightMm: 20,
      minDpi: 200,
      colorMode: 'Black or dark blue ink',
      background: 'white paper',
      allowBackgroundEdit: true,
      headSizePercent: null,
      maxPages: 1,
      notes: 'GATE signature aspect ratio must be 2:7 (e.g. 280×80 to 560×160 px), between 3 KB and 100 KB, signed with dark ink on white background.',
    },
    sourceUrl: 'https://gate2025.iitr.ac.in/',
    lastVerified: '2026-09-28',
    verifiedBy: 'GATE Official Application Guide',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'ssc-photo',
    country: 'India',
    organization: 'Staff Selection Commission (SSC)',
    portal: 'ssc.gov.in',
    documentType: 'SSC Candidate Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 20480, // 20 KB
      maxBytes: 51200, // 50 KB
      minWidth: 100,
      maxWidth: 150,
      minHeight: 120,
      maxHeight: 180,
      widthMm: 35,
      heightMm: 45,
      minDpi: 200,
      colorMode: 'RGB color',
      background: 'light background',
      allowBackgroundEdit: false,
      headSizePercent: { min: 70, max: 80 },
      maxPages: 1,
      notes: 'SSC online application photo must be between 20 KB and 50 KB, JPEG format, 100–120 px width by 120–140 px height.',
    },
    sourceUrl: 'https://ssc.gov.in/',
    lastVerified: '2026-09-28',
    verifiedBy: 'SSC Notice of Examination Guidelines',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'ssc-signature',
    country: 'India',
    organization: 'Staff Selection Commission (SSC)',
    portal: 'ssc.gov.in',
    documentType: 'SSC Candidate Signature',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 10240, // 10 KB
      maxBytes: 20480, // 20 KB
      minWidth: 100,
      maxWidth: 150,
      minHeight: 40,
      maxHeight: 70,
      widthMm: 40,
      heightMm: 20,
      minDpi: 200,
      colorMode: 'Black ink',
      background: 'white paper',
      allowBackgroundEdit: true,
      headSizePercent: null,
      maxPages: 1,
      notes: 'SSC signature must be between 10 KB and 20 KB, JPEG format, approximately 100–120 px width by 40–60 px height, signed with black pen.',
    },
    sourceUrl: 'https://ssc.gov.in/',
    lastVerified: '2026-09-28',
    verifiedBy: 'SSC Notice of Examination Guidelines',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'upsc-photo',
    country: 'India',
    organization: 'Union Public Service Commission (UPSC)',
    portal: 'upsconline.nic.in / upsc.gov.in',
    documentType: 'UPSC Civil Services Photo',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 20480, // 20 KB
      maxBytes: 307200, // 300 KB
      minWidth: 350,
      maxWidth: 1000,
      minHeight: 350,
      maxHeight: 1000,
      widthMm: 35,
      heightMm: 45,
      minDpi: 300,
      colorMode: 'RGB color',
      background: 'plain white background with name and date',
      allowBackgroundEdit: false,
      headSizePercent: { min: 70, max: 80 },
      maxPages: 1,
      notes: 'UPSC online photograph must be 350×350 to 1000×1000 pixels, between 20 KB and 300 KB in JPG format, 3/4 face visible on white background.',
    },
    sourceUrl: 'https://upsc.gov.in/',
    lastVerified: '2026-09-28',
    verifiedBy: 'UPSC Civil Services Examination Notice',
    status: 'verified',
    placeholder: false,
  },
  {
    id: 'upsc-signature',
    country: 'India',
    organization: 'Union Public Service Commission (UPSC)',
    portal: 'upsconline.nic.in / upsc.gov.in',
    documentType: 'UPSC Civil Services Signature',
    requirements: {
      formats: ['image/jpeg'],
      minBytes: 20480, // 20 KB
      maxBytes: 307200, // 300 KB
      minWidth: 350,
      maxWidth: 1000,
      minHeight: 350,
      maxHeight: 1000,
      widthMm: 40,
      heightMm: 20,
      minDpi: 300,
      colorMode: 'Black ink on white paper',
      background: 'white paper',
      allowBackgroundEdit: true,
      headSizePercent: null,
      maxPages: 1,
      notes: 'UPSC signature must be 350×350 to 1000×1000 pixels, between 20 KB and 300 KB in JPG format, signed in black ink on white paper.',
    },
    sourceUrl: 'https://upsc.gov.in/',
    lastVerified: '2026-09-28',
    verifiedBy: 'UPSC Civil Services Examination Notice',
    status: 'verified',
    placeholder: false,
  },
];
