import type { GuideSeed } from './guides-a';

export const GUIDES_B: GuideSeed[] = [
  {
    slug: 'shrink-photos-for-applications',
    h1: 'How to shrink photos for applications',
    keyword: 'shrink photos for applications',
    description: 'Shrink a photo before a form, without inventing the form’s limit. No upload. Keep a copy you can still read.',
    essay: 'Application forms often want a small photo of a document or a headshot. The number is the form’s number, and it changes. This site will not guess a passport office’s kilobyte cap. Shrink locally, read the size your system shows, and compare it with the number printed on that form. If the face or the stamp becomes unreadable, the file is too small even if it matches the cap. Keep the camera original. Send the smaller copy. A website that requires the upload before it tells you the limit has already taken the document.',
    steps: ['Read the limit on the form itself.', 'Resize on this device and check the stamp or the face.', 'Attach the copy that is both under the limit and still readable.'],
    points: ['The form’s own page is the source of the number.', 'Unreadability is a failed application even at the right size.', 'Do not upload the original to discover the limit.'],
    facts: [
      'This advice does not upload the application photo.',
      'The pixels are re-encoded. The camera original should stay in your library.',
      'A melted stamp will be rejected. A slightly larger readable file is the one to ask about if the cap is tight.',
      'Open the compressed photo at the size the form will show, not only as a thumbnail.',
      'You can shrink offline after the page loads, then reconnect only to submit the form yourself.',
    ],
    related: ['compress-image', 'compress-image-to-100kb', 'jpg-to-pdf'],
  },
  {
    slug: 'merge-pdfs-without-an-account',
    h1: 'Merge PDFs without an account',
    keyword: 'merge pdfs without an account',
    description: 'Combine PDFs without signing up. No upload. The order on screen is the order in the file.',
    essay: 'An account exists to store something. If the tool does not keep your file, it does not need your email. Merging is copying pages into one PDF in the order you choose. Drag the rows, then download. A site that demands a login before the merge is usually about to keep a project, a quota, or a mailing list. You can merge here without one. A locked source still has to be opened with a password you know; the merger will not invent one.',
    steps: ['Add the PDFs in any order.', 'Drag until the sequence is the one a reader should see.', 'Download the single file. No mailbox confirmation is part of the job.'],
    points: ['No account is created because the file is not stored.', 'Order is visible before you write the file.', 'A login wall is a different product.'],
    facts: [
      'Merging without an account also means the sources are not uploaded to create that account.',
      'Pages are copied. They are not retyped, and a locked file is not guessed open.',
      'Do not merge drafts you still need to compare. You will lose the side-by-side view.',
      'Check the first page, the last page, and the page count against your list.',
      'With Wi-Fi off after load, the merge still finishes. An account server would not.',
    ],
    related: ['merge-pdf', 'organize-pdf', 'compress-pdf'],
  },
  {
    slug: 'split-a-pdf-by-page-range',
    h1: 'Split a PDF by page range',
    keyword: 'split a pdf by page range',
    description: 'Extract a page range from a PDF in the browser. No upload. The download contains only the pages you named.',
    essay: 'A range is a cut. Pages 4–6 become a new file; the rest stay out of that download. Write the numbers down before you start, because page indexes in a viewer start at 1 and people still mix that up with a printed footer that says something else. Splitting does not shrink the pictures on the pages you keep and does not remove a sentence from a page you keep. If the goal is a smaller scan, compress after the cut, or instead of it.',
    steps: ['Note the page numbers you need, from the viewer’s count.', 'Extract that range locally.', 'Open the download and count. Then compress only if the cut is still too heavy.'],
    points: ['A range is not a rewrite.', 'Footer numbers and viewer numbers can disagree.', 'Omitted pages are not in the new file.'],
    facts: [
      'Splitting a range does not upload the pages you throw away or the pages you keep.',
      'The new file has the pages you named. It is not a compressed or searchable version of them.',
      'Do not use a split to hide text on a page that remains. That text is still there.',
      'Count pages in the download. If the footer says page 12 of 40, you extracted a piece of a larger document, which is fine if that is what you wanted.',
      'The cut still works offline after the tool has loaded.',
    ],
    related: ['split-pdf', 'organize-pdf', 'compress-pdf'],
  },
  {
    slug: 'organize-pages-before-you-send',
    h1: 'Organize pages before you send',
    keyword: 'organize pdf pages',
    description: 'Put PDF pages in order before you send them. No upload. The download follows the grid, not the scanner.',
    essay: 'Scanners and merged mail threads produce packets in the wrong order. The person who receives them should not have to reconstruct the story. Look at the grid, drag the cover to the front, drop blank pages, and rotate the one sideways sheet. Then download. The file follows that grid. Doing this locally matters because the disordered file is often the sensitive one: a application, a claim, a draft. You do not need an account to hold the arrangement while you think.',
    steps: ['Open the grid and find the page that should be first.', 'Drag, delete blanks, and rotate the exceptions.', 'Download and flip through once before you attach it.'],
    points: ['Order is part of the document.', 'Blanks and one sideways page are normal scanner mistakes.', 'Arrange before you compress or send.'],
    facts: [
      'Arranging pages does not upload the packet.',
      'The saved order is the on-screen order. Deleted pages are omitted.',
      'Organizing is not redaction. A page you keep still contains everything that was on it.',
      'The first page of the download should be the page you moved to the front.',
      'You can reorder offline after load. The thumbnails are drawn here.',
    ],
    related: ['organize-pdf', 'rotate-pdf', 'merge-pdf'],
  },
  {
    slug: 'turn-photos-into-a-pdf',
    h1: 'Turn photos into a PDF',
    keyword: 'photos to pdf',
    description: 'Make one PDF from photos on this device. No upload. Order them first, and do not expect OCR.',
    essay: 'A stack of photos becomes a PDF by placing each picture on a page. The order you leave is the order someone will scroll. Phone photos are large, so reducing them as they go in is usually right, unless you are archiving the camera files themselves. Those originals should stay in your library. The PDF is a delivery copy. It will not become searchable by being built. A picture of a receipt is still a picture. If a HEIC file will not open, the browser cannot decode it, and the fix is an export on the phone that took it, not an upload.',
    steps: ['Drop the photos and drag them into reading order.', 'Leave size reduction on unless you need every pixel.', 'Download the PDF and scroll it before you delete anything.'],
    points: ['Order is the story.', 'Originals stay originals.', 'HEIC opens only when the browser already can.'],
    facts: [
      'Building a PDF from photos does not upload the camera roll.',
      'Each picture becomes a page. Reduction is optional and local. No text layer is added.',
      'Do not throw away the only copy of a photo because a PDF exists. The PDF is a view, often a smaller one.',
      'Scroll the PDF. A sideways photo can be fixed by rotating the page or retaking the shot.',
      'After load, airplane mode still builds the PDF from pictures already on the device.',
    ],
    related: ['jpg-to-pdf', 'scan-to-pdf', 'compress-image'],
  },
  {
    slug: 'password-protect-a-pdf',
    h1: 'How to password-protect a PDF',
    keyword: 'password protect a pdf',
    description: 'What a PDF password really is. No upload. This version will not pretend a file is encrypted.',
    essay: 'A PDF password that matters is encryption. The bytes are scrambled until the password opens them. A “permissions” flag that any reader can ignore is not the same thing, and a ZIP password is not the same thing either. This version does not encrypt, and it will not show a lock on a file that is still readable everywhere. Use a desktop tool that names the algorithm, on this computer, if you need that. Do not upload the confidential file to a website whose only proof of encryption is an icon.',
    steps: ['Decide whether you need encryption or merely a warning not to edit.', 'Encrypt locally with a tool that can, and remember the password outside the file.', 'Open the result in a second viewer and confirm it asks.'],
    points: ['Encryption is not a badge.', 'This app will not fake the lock.', 'The password must not be the only copy, and it must not travel inside the file.'],
    facts: [
      'This guide does not collect a password from you.',
      'No encryption is applied here. An unprotected file stays unprotected.',
      'Do not email a file you only hope is locked. Test it in another viewer first.',
      'The test is a password prompt in a different program. No prompt means no encryption.',
      'Offline or not, this version still will not claim a new lock.',
    ],
    related: ['protect-pdf', 'unlock-pdf', 'watermark-pdf'],
  },
  {
    slug: 'remove-a-pdf-password-you-know',
    h1: 'Remove a PDF password you know',
    keyword: 'remove a pdf password',
    description: 'Removing a password is not guessing one. No upload. This version will not try passwords.',
    essay: 'If you know the password, a capable local tool can open the file and save a copy without encryption. That is a legitimate step when you are allowed to remove the restriction. If you do not know the password, the honest tools stop. Lists of common passwords, and websites that ask you to upload the locked file, are trying to break it. This app will not do that, and it also cannot strip encryption in this version. Unlock on a desktop tool you trust, on this device, then come back if you need to compress or merge the open file.',
    steps: ['Use the password you already know, in a local program that can remove it.', 'Do not paste that password into a website.', 'Bring the unlocked file back here only for a job this app actually does.'],
    points: ['Guessing is not a feature.', 'This version does not decrypt.', 'A password typed into an upload form is now theirs too.'],
    facts: [
      'Nothing on this page accepts a password to try against your file.',
      'Encryption stays in place here. There is no unlocked download from the Unlock screen.',
      'If you have forgotten the password, stop. A remover site is not a memory aid.',
      'A truly unlocked file opens in a second viewer with no prompt.',
      'The refusal is identical offline. No password list is fetched.',
    ],
    related: ['unlock-pdf', 'protect-pdf', 'repair-pdf'],
  },
  {
    slug: 'add-page-numbers',
    h1: 'How to add page numbers to a PDF',
    keyword: 'add page numbers to a pdf',
    description: 'Stamp page numbers onto a PDF locally. No upload. Skip a cover, and check the last page.',
    essay: 'Page numbers drawn into a PDF are part of the page, not a hint to the viewer. You choose the starting number and whether the first page is a cover that should stay blank. They will collide with a footer that is already there, so look at the corner on a busy page before you send a long packet. They do not repair a table of contents. If the contents say the budget is on page 4 and it is on page 7, fix the contents or the order; the stamp will only count what is in the file.',
    steps: ['Decide the start number and whether page 1 is a cover.', 'Stamp locally and look at a crowded corner.', 'Check the last page’s number against your count.'],
    points: ['Numbers follow the pages you have.', 'A cover can be skipped.', 'A table of contents is a separate problem.'],
    facts: [
      'Stamping numbers does not upload the PDF.',
      'The digits are drawn into the content. They are not a toggle the recipient can hide in every reader.',
      'Do not number a file to imply pages you deleted were never part of a larger document, if that implication would mislead.',
      'The last number should match the start value plus the pages you numbered.',
      'Numbering still runs with the network off after load.',
    ],
    related: ['add-page-numbers-to-pdf', 'organize-pdf', 'watermark-pdf'],
  },
  {
    slug: 'watermark-a-contract',
    h1: 'How to watermark a contract',
    keyword: 'watermark a pdf',
    description: 'Mark a draft contract without uploading it. No upload. A watermark is a label, not a lock and not redaction.',
    essay: 'A visible Draft mark keeps an early contract from being mistaken for the signed one. Draw it locally, in words you choose, and read a page to see that the clause underneath is still readable. The mark is not encryption. Anyone can read the draft. It is also not redaction: it does not hide a number. When the contract is final, produce a copy without the mark rather than asking the other party to ignore it. Saving a workflow that always stamps Draft is useful until the day you forget and send the stamped file.',
    steps: ['Type the mark you want, such as Draft.', 'Apply it locally and read a clause through the mark.', 'Keep an unmarked copy for the version you will actually sign.'],
    points: ['A watermark labels. It does not lock.', 'The text underneath remains.', 'Remove the mark before the final send.'],
    facts: [
      'Watermarking a draft does not upload the contract.',
      'The text you typed is drawn on the pages. It does not encrypt them and does not remove words.',
      'Do not watermark a figure in order to conceal it. Use real redaction, which this version does not fake.',
      'The mark should be readable, and so should the clause under it.',
      'You can stamp offline after load. Check that you meant to.',
    ],
    related: ['watermark-pdf', 'pdf-workflows', 'redact-pdf'],
  },
  {
    slug: 'repair-a-damaged-pdf',
    h1: 'How to repair a damaged PDF',
    keyword: 'repair a damaged pdf',
    description: 'What a limited PDF repair can fix. No upload. Missing bytes cannot be invented, and passwords are not guessed.',
    essay: 'Some PDFs fail in one viewer and open in another because the table that points at objects is damaged while the objects are still there. Reloading and saving can rebuild that table. It cannot recreate pages that were never in the download, and it cannot open a file that is actually a HTML error page saved with a .pdf name. If the app says the file could not be read as a PDF, export it again from the program that created it. Do not upload the broken contract to a repair service that keeps customer files “for quality”.',
    steps: ['Confirm the file is a PDF and not an error page renamed.', 'Try a local rebuild.', 'If it still will not open, export again from the source. Do not expect missing pages to reappear.'],
    points: ['A rebuild fixes structure, not absent bytes.', 'A password is a different problem.', 'The broken file stays on this device while you try.'],
    facts: [
      'A repair attempt does not upload the damaged file.',
      'A success rewrites the cross-reference. It does not decrypt and it does not hallucinate pages.',
      'If nothing can parse the header, stop. Another website will not have the missing half of your download.',
      'Open the result in the viewer that failed. If it opens, the rebuild was enough.',
      'The attempt does not need Wi-Fi after the app has loaded.',
    ],
    related: ['repair-pdf', 'unlock-pdf', 'compress-pdf'],
  },
];
