import type { GuideSeed } from './guides-a';

export const GUIDES_C: GuideSeed[] = [
  {
    slug: 'compare-two-contract-versions',
    h1: 'Compare two contract versions',
    keyword: 'compare two pdfs',
    description: 'Compare the words in two PDF drafts. No upload. Pictures are not part of the check, so read the pages too.',
    essay: 'Two drafts of a contract should be compared before you sign, and they should not have to sit on a stranger’s server to do it. A word difference shows insertions and deletions in the text layer. It will miss a logo that moved and a scan that has no text. Read the changed sentences in the actual pages. If the files are scans, this comparison will look empty, which means “no text”, not “no changes”. Get a text layer from a local OCR tool you trust before you compare, or compare the paper with your eyes.',
    steps: ['Export or save both drafts as PDFs with real text.', 'Run the word comparison locally.', 'Read every changed sentence on the page, not only in the diff list.'],
    points: ['Word diffs miss pure pictures.', 'Empty text is not a match.', 'Both files can stay on the device.'],
    facts: [
      'Comparing two drafts does not upload either contract.',
      'You see word changes from the text layers. A moved seal with the same words can be invisible to this check.',
      'Do not compare scans and treat silence as approval.',
      'Open both PDFs at the first change and read the clause.',
      'The comparison still runs offline after load.',
    ],
    related: ['compare-pdf', 'pdf-to-word', 'redact-pdf'],
  },
  {
    slug: 'pdf-to-word-what-you-keep',
    h1: 'PDF to Word: what you keep',
    keyword: 'pdf to word what you keep',
    description: 'What a local PDF to Word export keeps. No upload. You get the text layer, not the designer’s layout.',
    essay: 'A PDF does not store a Word document inside itself. It stores drawing instructions and, sometimes, text. Exporting to Word here copies that text into a simple document. Columns, text boxes, and exact line breaks are not rebuilt. A scan without a text layer contributes almost nothing, and this version will not OCR it to fill the gap. If you need the layout, go back to the original Word file. If you need the words and you can select them in the PDF, the local export is the private way to get them.',
    steps: ['Select a sentence in the PDF. If you cannot, stop. There is no text to export.', 'Export locally.', 'Find that same sentence in the document. Ignore the lost columns.'],
    points: ['Selectable text can move. Layout usually cannot.', 'Scans do not become prose here.', 'The original PDF remains the designed copy.'],
    facts: [
      'The export does not upload the PDF in exchange for a docx.',
      'Words from the text layer are kept in a simple file. Positioning is not a promise.',
      'A blank document means the PDF had no text layer, not that the exporter failed silently.',
      'Search the document for a sentence you selected in the PDF.',
      'Extraction works offline after the app has loaded.',
    ],
    related: ['pdf-to-word', 'pdf-to-markdown', 'ocr-pdf'],
  },
  {
    slug: 'word-to-pdf-what-changes',
    h1: 'Word to PDF: what changes',
    keyword: 'word to pdf what changes',
    description: 'What changes when a docx becomes a PDF here. No upload. Paragraphs are kept; complex layouts may shift.',
    essay: 'A docx is a zip of XML. This page reads the paragraphs and writes a PDF. It is a beta, and elaborate layouts can shift. Tables, text boxes, and headers may not land where Word showed them. That is a reason to export from Word itself when the letterhead must match. It is not a reason to upload the draft to a conversion website. If the document is ordinary paragraphs, the local PDF is enough. Remote images inside the docx are not fetched, for the same reason URLs are not fetched.',
    steps: ['If the file is simple prose, convert it here.', 'If it is a designed letter, export from the editor that built it.', 'Read the PDF next to the original before you send it.'],
    points: ['Paragraphs survive more often than layout.', 'Fetching images would leave the device, so they are not fetched.', 'The editor’s own export is the fidelity path.'],
    facts: [
      'Converting a docx does not upload it.',
      'You get PDF text of the paragraphs. A shifted table is an expected limit, not a silent success.',
      'Do not paste a web link and expect this page to download the document.',
      'Compare the PDF with Word on a page that has a table or a header.',
      'Once loaded, the conversion does not need the network, and it will not open one to fetch missing art.',
    ],
    related: ['word-to-pdf', 'html-to-pdf', 'pdf-to-word'],
  },
  {
    slug: 'html-to-pdf-without-fetching-the-web',
    h1: 'HTML to PDF without fetching the web',
    keyword: 'html to pdf offline',
    description: 'Turn HTML you already have into a PDF. No upload, and no request to the URL in the markup.',
    essay: 'Browsers are happy to render a page by fetching its images, fonts, and scripts. That is the opposite of a private conversion. This tool accepts markup you paste or a file you open, and it does not request the addresses inside it. You get the text. You do not get a pixel-perfect copy of a logged-in dashboard, because that dashboard only exists after scripts run and cookies are sent. If you need that screenshot, print from the browser while you are logged in, on your machine, and know that the print is a picture of what you already could see.',
    steps: ['Paste the HTML or open a local file.', 'Do not expect scripts or remote images to run.', 'Read the PDF. Missing figures were left out on purpose.'],
    points: ['No URL is fetched.', 'Scripts do not run.', 'A logged-in site is not something this page will go and get.'],
    facts: [
      'The HTML is not uploaded, and the links inside it are not requested.',
      'Local text becomes a simple PDF. Remote assets stay remote.',
      'Do not use this to archive a web app. Print that from the browser session you already have.',
      'If a picture is missing, view the source. Its address was not contacted.',
      'Pasted HTML still converts with Wi-Fi off, which is the proof no site was called.',
    ],
    related: ['html-to-pdf', 'word-to-pdf', 'pdf-to-markdown'],
  },
  {
    slug: 'what-a-browser-pdf-tool-can-and-cannot-do',
    h1: 'What a browser PDF tool can and cannot do',
    keyword: 'browser pdf tool limits',
    description: 'An honest map of what this browser app does. No upload. Unfinished jobs are labeled, not imitated.',
    essay: 'A browser can merge, split, reorder, rotate, crop, stamp numbers, watermark, compress images, build a PDF from pictures, render pages to JPEG, and pull a text layer into a simple document. It can do those without a server. It cannot, in this version, encrypt, decrypt, truly redact, OCR a scan, rebuild a spreadsheet, reconstruct slides, fill AcroForm fields, or apply a certificate. Those screens say so. A tool that shows a finished download for a job it cannot check is worse than a tool that refuses. Use a named desktop program on your computer for the refused jobs, still without uploading, if you need them today.',
    steps: ['Start from the tool page for the job, not from a slogan.', 'Read the one-line limit if the action is disabled.', 'Use a local desktop program for encryption, OCR, and true redaction.'],
    points: ['Implemented jobs run here.', 'Refused jobs are named.', 'A fake file is not a convenience.'],
    facts: [
      'Reading the map does not upload a PDF.',
      'Ready tools change the file locally. Limited tools change nothing and say why.',
      'Do not assume a long menu means every item is real. Open the item.',
      'Run one ready tool and one limited tool. Only the ready tool should offer a real download of that job.',
      'The limits are the same offline. Nothing becomes implemented when a server answers.',
    ],
    related: ['tools', 'edit-pdf', 'privacy'],
  },
  {
    slug: 'compress-images-for-email',
    h1: 'Compress images for email',
    keyword: 'compress images for email',
    description: 'Make photos small enough to attach. No upload. Your mail app’s own limit is the number that counts.',
    essay: 'Mail systems reject large attachments, and the cutoff depends on the account. This page will not print a vendor’s megabyte number from memory. Shrink the photos here, attach them, and read the warning your mail app shows. If it offers to turn the file into a cloud link, that is the mail company uploading, which you can decline by attaching the local file instead or by sending fewer pictures. JPEG is the usual choice for photos in mail. A PNG of a screenshot may not shrink until you resize it. Location data is not copied into the new file.',
    steps: ['Compress or resize the photos on this device.', 'Attach the downloads and read your mail app’s own warning.', 'Decline a cloud-link offer if you did not mean to upload.'],
    points: ['The mail app, not this page, enforces the cap.', 'A shared link is an upload by the mail service.', 'GPS data does not need to travel with the picture.'],
    facts: [
      'Shrinking for email does not upload the photos to this app.',
      'You get a new, usually smaller file. The camera original can stay in your library.',
      'Do not accept a “send as link” button if the point was to avoid another copy.',
      'The mail app should show a size when you attach. Compare it with the warning on that screen.',
      'Compress offline, then reconnect only when you are ready for the mail program to send.',
    ],
    related: ['compress-image', 'compress-pdf-for-email', 'jpg-to-webp'],
  },
  {
    slug: 'heic-photos-on-windows',
    h1: 'HEIC photos on Windows',
    keyword: 'heic to jpg on windows',
    description: 'Why HEIC may not open on Windows, and what not to do. No upload. Export JPEG on the phone if the browser cannot decode it.',
    essay: 'HEIC is a photo format common on iPhones. Windows browsers often cannot decode it, and this site will not add a decoder or upload the picture so a server can convert it. If the page says it cannot read the file, open the photo on the iPhone and export a JPEG, or use a codec you installed yourself on the PC. When a browser can decode HEIC, the JPEG is encoded locally. Expect the JPEG to be larger than the HEIC. That is normal. The small HEIC size was the point of the format.',
    steps: ['Try the file. If the browser cannot decode it, stop.', 'Export JPEG from the phone that took the photo.', 'Keep the HEIC if you still want the smaller original.'],
    points: ['No bundled HEIC decoder, on purpose.', 'No upload to borrow one.', 'A larger JPEG is expected.'],
    facts: [
      'A failed HEIC open does not fall back to an upload.',
      'When decode works, the new file is a JPEG made here. Detail already discarded stays discarded.',
      'Do not email the HEIC to a random converter site because a laptop cannot open it.',
      'Open the JPEG and look at the subject. Then decide whether the HEIC original still needs keeping.',
      'Offline, only a browser that already understands HEIC can convert it. Nothing is downloaded to add that ability.',
    ],
    related: ['heic-to-jpg', 'compress-image', 'jpg-to-pdf'],
  },
  {
    slug: 'offline-pdf-tools',
    h1: 'PDF tools that keep working offline',
    keyword: 'offline pdf tools',
    description: 'How to test that PDF tools work offline. No upload. Load first, then disconnect, then run the job.',
    essay: 'Offline does not mean the first visit needs no network. The program has to arrive. After it says it is on-device, disconnect and do the job. Compress, merge, or split a file you already have. If the tool asks you to reconnect, it was not offline. Installing the page as an app caches the program for next time. It must not cache your documents, and this one does not. Server logs may still show that you loaded the page earlier. They do not receive the PDF during the offline run, because there is no run to receive.',
    steps: ['Load the app and wait for the ready state.', 'Turn off Wi-Fi and run a real tool on a local file.', 'Turn the network back on only when you have the download you need.'],
    points: ['The test is a finished job with the network off.', 'The first load is allowed to use the network.', 'Documents are not what the app shell caches.'],
    facts: [
      'The test file is not uploaded before you disconnect. Disconnect first if you want to be strict, after the ready state.',
      'A completed download while offline is the result. An error that demands the network is a failed product.',
      'Do not confuse the browser’s own update check with the tool. The tool’s request list should stay on this origin.',
      'Repeat with merge and with an image, not only with a slogan page.',
      'Once loaded, the tools are the offline tools. This article is only the instruction.',
    ],
    related: ['offline-pdf-tools', 'pdf-tools-that-work-offline', 'compress-pdf'],
  },
  {
    slug: 'how-to-check-a-tool-does-not-upload',
    h1: 'How to check a tool does not upload',
    keyword: 'check pdf tool does not upload',
    description: 'A practical check that a PDF tool is not uploading. No upload. Use the network panel and the Wi-Fi test.',
    essay: 'Open the browser’s network panel, filter it, and note the origins before you add a file. Add a PDF and run the tool. New requests should stay on the same site, and they should be the app’s own files if any are still loading, not a POST of the document to an API. Then repeat with the network disabled after the ready state. A tool that passes both checks is not uploading. A tool that shows a progress label “uploading” has told you the truth. Ignore badges. A privacy policy is not a network log. This site expects to pass that test; if you ever see a document POST, treat it as a bug and stop using that build.',
    steps: ['Open the network panel before you drop a file.', 'Run the tool and look for a request to any other origin.', 'Disconnect and run it again. It should finish.'],
    points: ['The panel is the evidence.', 'Another origin, or a POST of the file, is an upload.', 'The offline rerun confirms it.'],
    facts: [
      'Performing the check does not require sending the PDF anywhere first.',
      'You are looking at requests, not at marketing copy. A document body in a request is a failure.',
      'A same-site request for the app’s script is not an upload of your file. A request that contains the file is.',
      'If you find a file upload, do not continue with a confidential document in that tab.',
      'The offline half of the check is decisive even if you do not enjoy the network panel.',
    ],
    related: ['privacy', 'compress-pdf-without-uploading', 'compress-pdf'],
  },
  {
    slug: 'how-pdf-compression-works',
    h1: 'How PDF compression works',
    keyword: 'how pdf compression works',
    description: 'What actually happens when a PDF gets smaller. No upload. Images are rewritten; text is left alone; smaller wins.',
    essay: 'Most “PDF compression” in a browser finds the images, draws them at a smaller size, encodes them as JPEG, and writes a new file if that file is smaller. Streams can be tidied. Metadata and unused objects can be dropped. Text that is real text is not the thing getting blurry, because it is not a picture. A scan has no such privilege: its letters are pixels. The pass stops being honest when it reports a size it did not measure or a quality score it did not compute. This app keeps the original when the new bytes are not smaller, and it will say so. That single rule is the difference between compression and a ritual.',
    steps: ['Look for images if the file is large.', 'Run a pass and read the resulting size.', 'Keep the original when the tool says nothing smaller was possible.'],
    points: ['Images are the lever.', 'Unmeasured quality scores are decoration.', 'Not smaller means keep the original.'],
    facts: [
      'Understanding the pass does not upload an example file.',
      'The new file replaces images when the encode is smaller. Text operators stay. A failed shrink returns the original.',
      'Do not trust a percentage with no before-and-after byte counts you can see.',
      'Compare the two sizes on disk, then read a scan line. Blocky type means the pixels were the text.',
      'The pass runs offline after load, which is also how you know the images were not sent out to be compressed.',
    ],
    related: ['compress-pdf', 'compress-pdf-to-100kb', 'compress-image'],
  },
];
