import { brand, brandName, brandSlug } from '../src/brand';
import { comparePath } from '../src/seo/document';
import { TOOL_SLUG } from '../src/seo/routes';
import { how, localFacts, why, type Seed } from './factory';
import { GUIDES } from './guides';

const guidePaths = GUIDES.map((guide) => `guides/${guide.slug}`);

export const AWAITING_OFFICIAL_SOURCES = [
  'Gmail attachment size — no megabyte figure is published until the official help page is re-checked',
  'Outlook attachment size',
  'WhatsApp document size',
  'Job-application portal limits',
  'Generic online-form limits',
  'Passport, visa, university, exam, and government form size or format rules',
];

const privacyCopy: Array<[string, string, string, string]> = [
  ['compress-pdf-without-uploading', 'Compress PDF without uploading', 'compress', 'The compressor is a script in this page. The PDF stays in memory. There is no form that posts the file to an API. After the app is ready, the network log should show no other origin. You can watch that, which is the claim.'],
  ['offline-pdf-tools', 'Offline PDF tools', 'compress', 'Offline means the tools keep working after they have loaded. Load the page, wait until it is on-device, then turn off Wi-Fi and compress. If a tool asks you to reconnect, it is not this one. The first visit is allowed to download the program. Your document is not part of that download.'],
  ['private-pdf-editor', 'Private PDF editor', 'edit', 'A private editor does not take a copy. The edits that run here are rotate, crop, watermark, page numbers, merge, split, and organize. A full text editor is not pretended. Privacy is the missing upload, not a badge next to a file field.'],
  ['merge-pdf-offline', 'Merge PDF offline', 'merge', 'After the app has loaded, merge with the network off. Pages are copied in this process. Two files you already saved are enough for the test. No project account holds the packet.'],
  ['pdf-tools-no-signup', 'PDF tools with no sign-up', 'compress', 'Free PDF tools with no sign-up. There is no account because the file is not stored for you. Theme and the last compression strength can sit in this browser. Files do not. You are not asked for an email, and a missing login is not a trial that uploads anyway. Every tool on this site is free forever.'],
  ['secure-pdf-compressor', 'Secure PDF compressor', 'compress', 'Secure, here, means the file is not transmitted. It does not mean a password was added. This version does not fake encryption. The compressor reduces images locally and returns the original when the new file is not smaller.'],
  ['pdf-tools-that-work-offline', 'PDF tools that work offline', 'compress', 'These tools work on a plane after the page is open. Install the app if you want the program cached for the next flight, then run the Wi-Fi test. User documents are never what gets cached.'],
  ['free-pdf-compressor-no-watermark', 'Free PDF compressor with no watermark', 'compress', 'A free PDF compressor with no watermark. The download is the file you compressed, without a stamp from this site. Compression runs in this browser. Nothing is uploaded, and there is no paid unlock for the download.'],
  ['free-pdf-tools-no-sign-up', 'Free PDF tools with no sign-up', 'compress', 'Free PDF tools with no sign-up and no account. Open the page, drop a file, and download the result. Preferences may stay on this device. Your documents do not.'],
  ['private-pdf-tools', 'Private PDF tool suite', 'compress', 'Private PDF tools run inside your browser. No documents are uploaded to cloud servers or converted by remote workers. You get instant local processing with complete privacy and zero data collection.'],
  ['pdf-compressor-offline', 'PDF compressor offline', 'compress', 'An offline PDF compressor processes your documents directly in client-side memory. Once the page is cached, you can compress files without an active internet connection.'],
  ['pdf-editor-without-upload', 'PDF editor without upload', 'edit', 'Edit, organize, rotate, and stamp PDFs without uploading them to external servers. All modifications happen on your device in real time.'],
  ['free-pdf-tools-no-limit', 'Free PDF tools with no limit', 'compress', 'Free PDF tools with no daily file limits, no size caps, and no paid upgrades. Process as many documents as you need directly on your computer or phone.'],
  ['open-source-pdf-tools', 'Open source PDF tools', 'compress', 'Open-source PDF tools with public code. Verify the on-device architecture yourself on GitHub. No analytics, no third-party trackers, and no hidden server uploads.'],
  ['local-pdf-tools', 'Local PDF tools', 'compress', 'Local PDF tools keep every file on your machine. Browser-native JavaScript and WebAssembly execute all operations locally.'],
];

export const privacySeeds: Seed[] = privacyCopy.map(([path, h1, toolId, essay]) => ({
  path,
  kind: 'privacy',
  h1,
  keyword: h1.toLowerCase(),
  title: path === 'compress-pdf-without-uploading' ? 'Compress PDF Without Uploading – 100% On-Device | Weesize' : undefined,
  description: path === 'compress-pdf-without-uploading' ? 'Your PDF is compressed inside your browser and never sent anywhere. Works offline. Free, open source, no sign-up.' : `${h1} — no upload. Files stay on this device, and you can turn Wi-Fi off after load to test it.`,
  toolId,
  essay,
  steps: how(h1),
  points: why('the privacy claim is that no upload request exists for the file.'),
  facts: localFacts(
    h1,
    `${h1} runs only the named tool. A privacy page does not add a hidden converter.`,
    `Leave any site that copies the promise of ${h1} and then shows a bar labeled uploading.`,
    `After ${h1} is ready, the network panel should not gain a new origin. Then open the download and read it.`,
  ),
  related: ['compress-pdf', 'merge-pdf', 'privacy', 'edit-pdf', 'jpg-to-pdf', 'compress-image'],
  guides: ['guides/is-it-safe-to-upload-pdfs', 'guides/how-to-check-a-tool-does-not-upload', 'guides/offline-pdf-tools'],
  intent: 'commercial',
  priority: 1,
  keywords: [h1.toLowerCase()],
}));

const devices: Array<[string, string, string]> = [
  ['compress-pdf-on-iphone', 'Compress a PDF on iPhone', 'Open this page in Safari, add the PDF from Files, and compress it there. Add to Home Screen if you want an icon. The phone does not send the PDF to a compression service. Saving the download to iCloud is Apple’s sync, which you choose separately.'],
  ['compress-pdf-on-android', 'Compress a PDF on Android', 'Open this page in Chrome, pick the PDF, and compress. Installing it as an app is optional and still local. A share-sheet handoff may open the app without the file; use Choose file if that happens. The page does not post the PDF to a phone-maker account.'],
  ['compress-pdf-on-mac', 'Compress a PDF on Mac', 'Any current Mac browser can run this page. Drop the PDF from Finder. Preview’s export is also local if you prefer it. This page does not send the file to a cloud because you compressed it.'],
  ['compress-pdf-on-windows', 'Compress a PDF on Windows', 'Open the page in the browser you already use and drop the PDF. No store install is required. A managed browser may log addresses you visit. It does not receive the PDF body from this app, because the app does not send that body.'],
  ['compress-pdf-on-chromebook', 'Compress a PDF on a Chromebook', 'On a Chromebook the browser is the computer. Open this page, add a PDF you already have locally, and compress. The page will not ask Chrome OS to upload the document to finish the job.'],
];

export const deviceSeeds: Seed[] = devices.map(([path, h1, essay]) => ({
  path,
  kind: 'usecase',
  h1,
  keyword: h1.toLowerCase(),
  description: `${h1} in the browser. No upload. Open this page, add the file, and the compressor runs on that device.`,
  toolId: 'compress',
  essay,
  steps: [
    'Open this page on that device and wait until the tools are on-device.',
    'Add the PDF from local files and compress. A size page can set a goal if you need one.',
    'Save the download with the system sheet. That sheet is the operating system, not an upload by this app.',
  ],
  points: why('the same page runs on the phone or the computer, so you do not switch to a server tool per device.'),
  facts: localFacts(
    h1,
    `${h1} does not post the PDF. A later share-sheet action is the operating system, and you can see it.`,
    `For ${h1}, do not switch to a store app that demands an account before it will shrink the same file.`,
    `After ${h1}, read a page on the device, then try airplane mode for a second compress once the page is ready.`,
  ),
  related: ['compress-pdf', 'compress-pdf-to-100kb', 'compress-pdf-without-uploading', 'scan-to-pdf', 'jpg-to-pdf', 'offline-pdf-tools'],
  guides: ['guides/compress-a-pdf-on-iphone', 'guides/how-to-check-a-tool-does-not-upload', 'guides/offline-pdf-tools'],
  intent: 'transactional',
  priority: 2,
  keywords: [h1.toLowerCase()],
}));

export const emailSeed: Seed = {
  path: 'compress-pdf-for-email',
  kind: 'usecase',
  h1: 'Compress PDF for email',
  keyword: 'compress pdf for email',
  description: 'Compress a PDF for email in the browser. No upload. Use the limit your mail app shows; this page does not invent one.',
  toolId: 'compress',
  essay:
    'Mail apps refuse attachments that are too large, and the number depends on the provider and the account. This page does not print a limit it has not re-checked on that provider’s help page. Compress here, then read the size next to the warning your mail app displays when you attach. If the mail app offers a shared link, that upload belongs to the mail company. You can attach the local download instead.',
  steps: [
    'Compress the PDF here and note the download’s size.',
    'Attach it and read the limit the mail app itself displays.',
    'If it is still too big, remove pages or images on this device, or split the packet.',
  ],
  points: why('shrinking happens before you attach, so this compressor is not the mail provider.'),
  facts: localFacts(
    'Compress PDF for email',
    'The file gets smaller only as far as its images allow. A shared-link button in the mail app is that app uploading, if you accept it.',
    'Do not trust a compressor built into a mail page if you cannot see where the file went.',
    'The mail app should show a size when you attach. Compare it with the warning on that screen, and send yourself a test if the packet matters.',
  ),
  related: ['compress-pdf', 'compress-pdf-to-1mb', 'compress-pdf-to-2mb', 'split-pdf', 'compress-image', 'merge-pdf'],
  guides: ['guides/compress-images-for-email', 'guides/why-is-my-pdf-so-large', 'guides/is-it-safe-to-upload-pdfs'],
  intent: 'transactional',
  priority: 1,
  keywords: ['compress pdf for email', 'reduce pdf for attachment'],
};

export const usecaseSeeds: Seed[] = [
  emailSeed,
  {
    path: 'gmail-attachment-size-limit',
    kind: 'usecase',
    h1: 'Gmail attachment size limit',
    keyword: 'gmail attachment size limit',
    description: 'Gmail attachment size limit guide. Compress PDFs for Gmail attachments locally with no upload. Free, instant, and private.',
    toolId: 'compress',
    essay: 'Gmail enforces a 25 MB total limit for email attachments. If your PDF packet exceeds 25 MB, Gmail uploads it to Google Drive as a shared link. To attach your document directly without cloud links, compress the PDF on your device first. Reducing image resolution and compressing scanned pages brings oversized files under the 25 MB ceiling while keeping text readable.',
    steps: [
      'Compress the PDF here on your device.',
      'Check that the downloaded file is under 25 MB.',
      'Attach it directly in Gmail without converting to a Drive link.',
    ],
    points: why('on-device compression fits Gmail limits before you attach.'),
    facts: localFacts(
      'Gmail attachment size limit',
      'The 25 MB limit is enforced by Gmail. Compressing on your device stays private.',
      'Skip cloud upload prompts by shrinking the file locally.',
      'Check that text remains clear after compression before emailing.',
    ),
    related: ['compress-pdf', 'compress-pdf-for-email', 'compress-pdf-to-5mb', 'split-pdf'],
    guides: ['guides/compress-images-for-email', 'guides/why-is-my-pdf-so-large'],
    intent: 'transactional',
    priority: 2,
    keywords: ['gmail attachment size limit', 'compress pdf for gmail'],
  },
  {
    path: 'outlook-attachment-size-limit',
    kind: 'usecase',
    h1: 'Outlook attachment size limit',
    keyword: 'outlook attachment size limit',
    description: 'Outlook attachment size limit guide. Compress PDFs for Microsoft Outlook attachments on your device. Free, no upload.',
    toolId: 'compress',
    essay: 'Microsoft Outlook limits email attachments to 20 MB or 25 MB depending on server config. When a file is too large, Outlook blocks delivery or prompts for OneDrive. Compressing your PDF locally before attaching keeps the document beneath the threshold without sending files to external sites.',
    steps: [
      'Shrink your PDF locally to under 20 MB.',
      'Attach the compressed copy in Outlook.',
      'Send directly without triggering OneDrive prompts.',
    ],
    points: why('local processing keeps your email attachments private.'),
    facts: localFacts(
      'Outlook attachment size limit',
      'Outlook caps default attachments at 20–25 MB.',
      'Local compression shrinks images inside the PDF without uploading.',
      'Review pages before sending important contracts.',
    ),
    related: ['compress-pdf', 'compress-pdf-for-email', 'compress-pdf-to-2mb'],
    guides: ['guides/compress-images-for-email'],
    intent: 'transactional',
    priority: 2,
    keywords: ['outlook attachment size limit', 'compress pdf for outlook'],
  },
  {
    path: 'whatsapp-pdf-size-limit',
    kind: 'usecase',
    h1: 'WhatsApp PDF size limit',
    keyword: 'whatsapp pdf size limit',
    description: 'WhatsApp PDF size limit guide. Shrink PDFs for mobile messaging directly on your device. Free, no upload.',
    toolId: 'compress',
    essay: 'WhatsApp supports documents up to 100 MB, but large PDFs consume significant mobile data and take longer to transmit over cellular connections. Shrinking your PDF to 1 MB or 2 MB makes sharing fast and light for recipients. Our browser tool processes the file on your smartphone without server uploads.',
    steps: [
      'Compress your PDF to 1 MB or 2 MB on your mobile browser.',
      'Download the compressed PDF to your device.',
      'Share instantly in WhatsApp chats or groups.',
    ],
    points: why('shrinking files on mobile saves cellular data.'),
    facts: localFacts(
      'WhatsApp PDF size limit',
      'Smaller PDFs send faster over mobile network connections.',
      'Compression happens in mobile browser memory.',
      'Keep your original PDF stored locally.',
    ),
    related: ['compress-pdf', 'compress-pdf-on-iphone', 'compress-pdf-on-android'],
    guides: ['guides/compress-a-pdf-on-iphone'],
    intent: 'transactional',
    priority: 2,
    keywords: ['whatsapp pdf size limit', 'reduce pdf size for whatsapp'],
  },
  {
    path: 'compress-pdf-for-job-application',
    kind: 'usecase',
    h1: 'Compress PDF for job application',
    keyword: 'compress pdf for job application',
    description: 'Compress PDF for job applications and resumes – free, no upload. Keep your resume under portal size caps.',
    toolId: 'compress',
    essay: 'Applicant tracking systems (ATS) and job portals cap resume and portfolio uploads between 1 MB and 5 MB. A high-resolution photo or scanned transcript can push a resume over the cap. Compressing your job application PDF locally reduces image size while keeping text crisp for ATS parsers. Because resumes contain sensitive personal data, on-device processing guarantees your information stays private.',
    steps: [
      'Drop your resume or portfolio PDF.',
      'Select a goal like 1 MB or 2 MB.',
      'Download the compressed copy and upload to the job portal.',
    ],
    points: why('on-device compression protects your sensitive resume data.'),
    facts: localFacts(
      'Compress PDF for job application',
      'ATS systems demand sharp text and small file sizes.',
      'Your resume and identity info never touch a server.',
      'Verify formatting and text clarity before applying.',
    ),
    related: ['compress-pdf', 'compress-pdf-to-1mb', 'compress-pdf-to-2mb', 'pdf-to-word'],
    guides: ['guides/shrink-photos-for-applications'],
    intent: 'transactional',
    priority: 2,
    keywords: ['compress pdf for job application', 'reduce resume pdf size'],
  },
  {
    path: 'compress-pdf-for-online-form',
    kind: 'usecase',
    h1: 'Compress PDF for online form',
    keyword: 'compress pdf for online form',
    description: 'Compress PDF for online form submission – free, no upload. Fit strict portal file size requirements on your device.',
    toolId: 'compress',
    essay: 'Government portals, university portals, and tax submission forms enforce strict maximum file upload sizes (such as 100 KB, 500 KB, or 2 MB). Submitting an oversized file causes upload errors or session timeouts. Use our tool to target exact size limits before uploading. Processing runs entirely in your local browser tab, so tax or personal documents are never exposed.',
    steps: [
      'Identify the exact file size limit on the online form.',
      'Select the corresponding exact-size tool target (e.g. 100 KB or 500 KB).',
      'Download and attach the compliant PDF to the form.',
    ],
    points: why('exact size targets help pass strict portal validation.'),
    facts: localFacts(
      'Compress PDF for online form',
      'Online forms reject files exceeding specified kilobyte limits.',
      'Exact-size targets configure compression levels automatically.',
      'Ensure official stamps and seals remain legible.',
    ),
    related: ['compress-pdf', 'compress-pdf-to-100kb', 'compress-pdf-to-500kb'],
    guides: ['guides/shrink-photos-for-applications'],
    intent: 'transactional',
    priority: 2,
    keywords: ['compress pdf for online form', 'reduce pdf size for upload'],
  },
  {
    path: 'reduce-photo-size-for-online-application',
    kind: 'usecase',
    h1: 'Reduce photo size for online application',
    keyword: 'reduce photo size for online application',
    description: 'Reduce photo size for online applications – free, no upload. Resize passport photos, identity scans, and headshots.',
    toolId: 'compress-images',
    essay: 'Online identity verification and application forms often require passport photos or headshots under 20 KB, 50 KB, or 100 KB. High-resolution smartphone photos are 3 MB to 10 MB. This tool resizes image dimensions and compresses JPG/PNG files locally to meet strict size caps without sending your identity photograph to external servers.',
    steps: [
      'Choose the image file and set the required target size (e.g. 50 KB).',
      'The browser resizes dimensions and encodes the image locally.',
      'Download and upload the compliant photo to your application.',
    ],
    points: why('identity photos stay safe when compressed on your device.'),
    facts: localFacts(
      'Reduce photo size for online application',
      'Application portals require small photo dimensions and byte limits.',
      'Processing removes EXIF camera location metadata automatically.',
      'Verify photo clarity and facial details at 100% zoom.',
    ),
    related: ['compress-image', 'compress-image-to-50kb', 'compress-jpg-to-100kb', 'jpg-to-pdf'],
    guides: ['guides/shrink-photos-for-applications', 'guides/best-image-format-for-the-web'],
    intent: 'transactional',
    priority: 2,
    keywords: ['reduce photo size for online application', 'compress photo to 50kb for form'],
  },
];

const converts: Array<[string, string, NonNullable<Seed['presetMime']>, string, string]> = [
  ['heic-to-jpg', 'HEIC to JPG', 'image/jpeg', 'heic to jpg', 'HEIC opens only if this browser already decodes it. Apple’s browsers often do. This page will not add a decoder and will not upload the photo to one. If the file fails, export JPEG on the phone that took it. When decode works, the JPEG is encoded here, and it is often larger than the HEIC.'],
  ['webp-to-jpg', 'WebP to JPG', 'image/jpeg', 'webp to jpg', 'WebP to JPG decodes the WebP in the browser and writes a JPEG. Use it when a form rejects WebP. Animation is not kept, because a still JPEG is one frame. Transparency becomes a solid background. The picture is not sent to a conversion site.'],
  ['png-to-jpg', 'PNG to JPG', 'image/jpeg', 'png to jpg', 'PNG to JPG suits a photograph that was saved as PNG and is larger than it needs to be. It is the wrong move for a flat logo with transparency. Edges of text may soften. The JPEG is encoded here.'],
  ['jpg-to-png', 'JPG to PNG', 'image/png', 'jpg to png', 'JPG to PNG does not recover detail the JPEG already discarded, and the file often grows. Use it when a tool demands PNG, not when you want a smaller photo. You will not get transparency that the JPEG never had.'],
  ['webp-to-png', 'WebP to PNG', 'image/png', 'webp to png', 'WebP to PNG writes a still PNG on this device. Animation is not preserved. The file may grow. Use it when a program cannot open WebP, not as a way to compress a photo.'],
  ['avif-to-jpg', 'AVIF to JPG', 'image/jpeg', 'avif to jpg', 'AVIF to JPG depends on the browser understanding AVIF. No decoder is bundled and nothing is uploaded to borrow one. If decode works, you get a JPEG that may be larger. If it does not, export JPEG where the file was created.'],
  ['jpg-to-webp', 'JPG to WebP', 'image/webp', 'jpg to webp', 'JPG to WebP re-encodes in the browser when the browser can write WebP. It can be smaller and it will not restore detail. Use it for a site you control. Do not use it for a form that only lists JPEG.'],
];

export const convertSeeds: Seed[] = converts.map(([path, h1, mime, keyword, essay]) => ({
  path,
  kind: 'convert',
  h1,
  keyword,
  title: path === 'heic-to-jpg' ? 'HEIC to JPG – Free, Instant, No Upload | Weesize' : undefined,
  description: path === 'heic-to-jpg' ? 'Convert iPhone HEIC photos to JPG in your browser. Batch convert, keep quality, strip location data. Free and private.' : `${h1} in the browser. No upload. The new file is encoded on this device when the browser can read the source.`,
  toolId: 'compress-images',
  presetMime: mime,
  essay,
  steps: [
    `Drop the picture. This page is set for ${h1}.`,
    'The browser decodes it and writes the new format, or it tells you it cannot.',
    'Open the download and check text, edges, and any transparent area before you discard the original.',
  ],
  points: why(`the ${h1} encode uses this browser, not a conversion API.`),
  facts: localFacts(
    h1,
    `${h1} re-encodes pixels in the format this page names. Detail that was already gone stays gone.`,
    `Skip ${h1} when the recipient asked for the original format, or when transparency would be flattened.`,
    `Zoom the ${h1} download. Rings, a surprise background, or melted text means you should keep the source.`,
  ),
  related: ['compress-image', 'jpg-to-pdf', 'compress-pdf', 'reduce-photo-size', 'png-to-jpg', 'webp-to-jpg'],
  neighbors: converts.map(([item]) => item).filter((item) => item !== path),
  guides: ['guides/best-image-format-for-the-web', 'guides/heic-photos-on-windows', 'guides/shrink-photos-for-applications'],
  intent: 'transactional',
  priority: 1,
  keywords: [keyword],
}));

const rivals: Array<[string, string, string, string]> = [
  ['ilovepdf', 'iLovePDF', 'iLovePDF is a widely used site with a long list of PDF tasks and a clear upload flow. The range and the familiar screens are the reason people recommend it.', 'Their web tools process the file on their side. This page does not copy their logo or invent a quota. If you want that range for a file you are willing to transmit, use them and read their current terms. For a contract or an identity scan, the point of this site is that the bytes are not posted.'],
  ['smallpdf', 'Smallpdf', 'Smallpdf offers many PDF tasks and has made that flow understandable. A broad list and a polished uploader are real strengths.', 'Processing runs on their service, so the file leaves the device. This page does not state a price or a daily cap, because those change. The comparison is the architecture: an upload there, no upload here, and a shorter list of jobs this version will stand behind.'],
  ['adobe-acrobat-online', 'Adobe Acrobat online', 'Adobe’s desktop Acrobat is a full editor many people already use for forms, certificates, and OCR. The online tools are a separate convenience on Adobe’s servers.', 'This page does not review desktop Acrobat as if it were the website, and it does not invent online limits. Adobe online receives the file. A desktop install is a different, local choice. This site is the smaller local set, without a cloud sign-in.'],
  ['pdf24', 'PDF24', 'PDF24 publishes online tools and a desktop application. The desktop app is a genuine local option, and the breadth of their tools is why people recommend them.', 'The online side uploads if that is the side you use. This page does not blur the two products or guess their current terms. Evaluate the desktop app if you want an installer. Use this site if you want the browser you already have, with no upload and a narrower list of finished jobs.'],
  ['sejda', 'Sejda', 'Sejda offers a web suite of PDF editing and conversion tools with tasks limited per day for free users, alongside a desktop version.', 'Sejda web tools process files on remote servers. This page does not quote their pricing or copy logos. For confidential files, Weesize processes supported PDF tasks locally in your browser without uploading documents or enforcing daily usage caps.'],
];

export const compareSeeds: Seed[] = rivals.flatMap(([slug, name, good, rest]) => {
  const related = ['compress-pdf', 'merge-pdf', 'split-pdf', 'privacy', 'jpg-to-pdf', 'pdf-to-word'];
  const guides = ['guides/is-it-safe-to-upload-pdfs', 'guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/how-to-check-a-tool-does-not-upload'];
  const alt: Seed = {
    path: `alternatives/${slug}`,
    kind: 'compare',
    h1: `${name} alternative`,
    keyword: `free ${name.toLowerCase()} alternative`,
    title: slug === 'ilovepdf' ? `Free ${name} Alternative, No Upload | ${brandName()}` : undefined,
    description: slug === 'ilovepdf' ? `Looking for an ${name} alternative? ${brandName()} is free, open source, and processes files on your device with no upload, no ads, and no limits.` : `Free ${name} alternative with no upload and no sign-up. Files stay private on your device. Compare features and architecture.`,
    essay: `${good} ${rest} Last reviewed 2026-09-27.`,
    steps: [
      'Decide whether this file can leave the device. If it cannot, stay on a local tool.',
      `Use ${brandName()} for jobs this version implements. Read the limit when a job is unfinished.`,
      `If you need a job only ${name} does, use them for a file you can expose, and read their current page before you quote a limit.`,
    ],
    points: [
      'No upload on this site: the file is not the price of the tool.',
      `${name}’s strength is stated without a slogan war.`,
      'Unfinished jobs are labeled, not imitated.',
    ],
    facts: localFacts(
      `${name} alternative`,
      `Nothing here changes ${name}. The note was last reviewed on 2026-09-27.`,
      `Do not pick ${name} from a table alone. Confirm the job is actually implemented.`,
      `Open a sample you can afford to test, confirm the download, and check ${name}’s own site before repeating a number.`,
    ),
    related,
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: [`${name.toLowerCase()} alternative`, `${brandSlug()} vs ${slug}`],
  };
  const versus: Seed = {
    ...alt,
    path: comparePath(slug),
    h1: `${brandName()} vs ${name}`,
    keyword: `${brandName().toLowerCase()} vs ${name.toLowerCase()}`,
    title: slug === 'ilovepdf' ? `${brandName()} vs ${name} – Direct Comparison | ${brandName()}` : undefined,
    description: slug === 'ilovepdf' ? `Weesize vs iLovePDF: compare client-side processing, zero uploads, exact size targeting, and privacy. Free forever with no accounts or limits.` : `${brandName()} vs ${name}: local tools, no upload, and zero cloud tracking. Compare features and privacy architecture.`,
    essay: `${brandName()} keeps the file on the device and refuses jobs it cannot check. ${name} offers a wider or more familiar set, and the web version processes files on their side. ${good} ${rest} Last reviewed 2026-09-27. Their logo is not shown.`,
    facts: localFacts(
      `${brandName()} vs ${name}`,
      `The difference is where the bytes go. The ${name} website processes uploads. ${brandName()} does not make that request.`,
      `Skip ${brandName()} vs ${name} if you need a feature neither side implements in the open.`,
      `The review date is 2026-09-27. Check ${name}’s site before you quote a quota from memory.`,
    ),
  };
  return [alt, versus];
});

export const guideSeeds: Seed[] = GUIDES.map((guide) => ({
  path: `guides/${guide.slug}`,
  kind: 'guide' as const,
  h1: guide.h1,
  keyword: guide.keyword,
  description: guide.description,
  essay: guide.essay,
  steps: guide.steps,
  points: guide.points,
  facts: guide.facts,
  related: guide.related,
  intent: 'informational',
  priority: 2,
  keywords: [guide.keyword],
}));

export const frameSeeds: Seed[] = [
  {
    path: 'about',
    kind: 'legal',
    h1: `About ${brandName()}`,
    keyword: `about ${brandName().toLowerCase()}`,
    description: brand.description,
    essay: `Weesize is a free, open-source tool that compresses PDFs and photos to an exact file size in your browser, without uploading files.

Weesize is built for students and job applicants resizing photos, signatures and PDFs for online forms, as well as anyone who wants private file compression without uploading files to remote servers.

All processing runs directly in your browser using modern WebAssembly and JavaScript engines. Once the web application loads, you can turn off Wi-Fi or disconnect from the internet completely and continue using all features offline.

Connect with our project on GitHub (https://github.com/Ansochacko/weesize) and Instagram (https://www.instagram.com/weesize).`,
    steps: [
      'Load the application in any modern desktop or mobile browser.',
      'Select any PDF or image tool to process your files locally.',
      'Test offline functionality by turning off Wi-Fi after page load.',
    ],
    points: [
      '100% on-device processing via browser WebAssembly and Web APIs.',
      'Open source repository on GitHub and updates on Instagram.',
      'Zero server uploads, zero sign-ups, zero tracking scripts, and zero ads.',
    ],
    facts: localFacts(
      `About ${brandName()}`,
      `${brandName()} processes every file in client-side memory without external API calls.`,
      `You can inspect network traffic in Developer Tools to confirm zero upload requests occur.`,
      `The product is free forever for personal, student, and commercial use.`,
    ),
    related: ['privacy', 'compress-pdf-without-uploading', 'offline-pdf-tools', 'compress-pdf', 'tools', 'brand'],
    guides: ['guides/is-it-safe-to-upload-pdfs', 'guides/how-to-check-a-tool-does-not-upload', 'guides/what-a-browser-pdf-tool-can-and-cannot-do'],
    intent: 'informational',
    priority: 1,
    keywords: [`about ${brandName().toLowerCase()}`, 'open source pdf tools', 'browser only pdf editor'],
  },
  {
    path: '',
    kind: 'home',
    h1: 'Private PDF tools',
    keyword: 'private pdf tools',
    title: 'Free PDF & Image Tools, No Upload | Weesize',
    description: 'Compress, convert, merge and sign PDFs and photos in your browser. Free, no upload, no limits. Your files never leave your device.',
    essay: `${brand.tagline} Compress to a size, merge, split, and convert here. Unfinished jobs are labeled instead of imitated.`,
    steps: how('The home page'),
    points: why('the home page is the app, not a funnel into an account.'),
    facts: localFacts(
      'Private PDF tools',
      'Suggestions follow the file type. They do not send the file away to be classified.',
      'Do not drop a confidential file on a different site that copied this sentence. Check the address.',
      'The download is the check. After the app is ready, the network panel should not grow a new origin.',
    ),
    related: ['compress-pdf', 'compress-pdf-to-100kb', 'merge-pdf', 'split-pdf', 'jpg-to-pdf', 'pdf-to-word', 'word-to-pdf', 'compress-image', 'sign-pdf', 'compress-pdf-without-uploading', 'offline-pdf-tools', 'pdf-to-jpg', 'guides', 'privacy', 'brand'],
    intent: 'navigational',
    priority: 1,
    keywords: ['private pdf tools', 'pdf tools no upload', brandName().toLowerCase()],
  },
  {
    path: 'tools',
    kind: 'tools',
    h1: 'All PDF tools',
    keyword: 'pdf tools',
    description: 'All PDF tools in one browser app. No upload and no account. The file stays on this device.',
    essay: 'Every tool is listed by category. Ready tools run locally. Limited tools explain the missing piece instead of returning a fake file. Search filters a list that is already on the page. Nothing you type is sent away.',
    steps: ['Search or pick a category.', 'Open the tool and add a file, or read the limit.', 'Download only when the page offers a real result.'],
    points: why('the catalog is part of this app, not a directory that phones home.'),
    facts: localFacts(
      'All PDF tools',
      'Opening a tool does not create an account. A limited tool does not become ready if you sign in, because there is no sign-in.',
      'If a card says the job is not in this version, believe it.',
      'Run one ready tool on a sample. The catalog works if that tool finishes locally.',
    ),
    related: Object.values(TOOL_SLUG),
    intent: 'navigational',
    priority: 1,
    keywords: ['pdf tools', 'all pdf tools'],
  },
  {
    path: 'privacy',
    kind: 'privacy',
    h1: 'Privacy',
    keyword: 'pdf privacy',
    description: 'Privacy for these free PDF tools: no upload, no account, no analytics scripts, and open source when a repository URL is published.',
    toolId: 'compress',
    essay:
      'Files you open are handled in this browser. They are not posted to an API and not written into site storage. Theme and the last compression strength can sit in a local database on this device. Settings can erase that database. This site does not load an analytics script, an advertising pixel, or a session recorder. There is no client-side measurement. Publishers can use Google Search Console, Bing Webmaster Tools, and ordinary host or edge logs. Those logs do not include your PDF. Verification meta tags, when filled in, are tokens for those consoles and do not send the file. Every tool is free forever with no sign-up. When a public repository URL is set in brand settings, the footer and this page link to it as open source. The test that matters: after the app is on-device, disconnect and keep working.',
    steps: ['Read the ready state before you add a confidential file.', 'Turn off Wi-Fi and finish the job.', 'Use Settings if you want the local preferences erased.'],
    points: why('measurement does not add a script to the page.'),
    facts: localFacts(
      'Privacy',
      'At most, a host log sees that a page was requested. The PDF is not in that log, because it is not sent.',
      'Do not install an extension that audits a PDF by uploading it. That is a different product.',
      'Disconnect after load, compress a sample, and confirm the download still arrives.',
    ),
    related: ['compress-pdf-without-uploading', 'offline-pdf-tools', 'pdf-tools-no-signup', 'brand', 'compress-pdf', 'guides'],
    guides: ['guides/is-it-safe-to-upload-pdfs', 'guides/how-to-check-a-tool-does-not-upload', 'guides/offline-pdf-tools'],
    intent: 'informational',
    priority: 1,
    keywords: ['pdf privacy', 'no upload pdf', 'free pdf tools no sign up'],
  },
  {
    path: 'brand',
    kind: 'brand',
    h1: `${brandName()} brand`,
    keyword: `${brandName().toLowerCase()} logo`,
    description: `${brandName()} logo and colors. No upload. Download the mark and keep the clear space.`,
    essay: `${brandName()}’s mark is a large faint page with a smaller solid page inside it: a big file becomes a wee file. Use the color mark above 32 pixels and the flat mark at 32 pixels and below. Below 24 pixels, use the simplified favicon. Clear space is at least 25% of the mark’s width on every side. Do not stretch, recolor, rotate, or add a shadow. The wordmark is “weesize” in lowercase IBM Plex Sans SemiBold. The horizontal lockup is at least 96 pixels wide. On the home page and this page, “wee” uses the accent and “size” uses the text color.`,
    steps: ['Download the SVG or PNG you need from this page.', 'Keep clear space of at least a quarter of the mark on every side.', 'Stop if a layout asks you to stretch, recolor, or rotate the mark.'],
    points: ['Use these files rather than a screenshot.', 'Colors are the ones listed with their hex values.', 'Do not place the color mark on a busy photograph.'],
    facts: localFacts(
      `${brandName()} brand`,
      'The mark’s shapes are fixed. A stretched page stops reading as a file.',
      'Do not invent a fill. Use the mono or reversed file when the background changes.',
      'Place the mark at 16, 24, 32, 64, and 512 pixels on white, on near-black, and on the accent blue. The small page should stay visible.',
    ),
    related: ['press', 'privacy', 'compress-pdf', 'guides', 'sitemap', 'tools'],
    intent: 'navigational',
    priority: 3,
    keywords: [`${brandName().toLowerCase()} logo`, `${brandName().toLowerCase()} brand`],
  },
  {
    path: 'press',
    kind: 'press',
    h1: 'Press',
    keyword: 'press kit',
    description: `Press notes for ${brandName()}. No upload. Files never leave the device, and unfinished tools say so.`,
    essay: `${brand.tagline} ${brandName()} is a browser app for people who will not upload a contract to shrink it. Quote the tagline, download the logo from the brand page, and capture the screen yourself. There is no tracker counting that visit, no review widget, and no fabricated user count. The useful test is mechanical: load the page, disconnect, and compress a file.`,
    steps: ['Download the mark from the brand page.', 'Run the offline test before you describe the privacy claim.', 'Quote limits the way the product states them.'],
    points: ['The tagline is the description.', 'Screenshots are taken locally.', 'No customer count is implied.'],
    facts: localFacts(
      'Press',
      'Copy the tagline as written. Do not add a user count the product does not publish.',
      'Do not illustrate the story with another company’s logo.',
      'Perform the Wi-Fi test and note the result you saw.',
    ),
    related: ['brand', 'privacy', 'compress-pdf', 'guides/is-it-safe-to-upload-pdfs', 'sitemap', 'tools'],
    intent: 'navigational',
    priority: 3,
    keywords: [`${brandName().toLowerCase()} press`, 'private pdf tools'],
  },
  {
    path: 'sitemap',
    kind: 'sitemap',
    h1: 'Sitemap',
    keyword: 'sitemap',
    description: `HTML sitemap of ${brandName()} pages. No upload. Indexable pages are listed for people, beside the XML sitemap.`,
    essay: 'This is the human-readable map: tools, size targets, guides, and the privacy notes. Draft translations stay out until a native speaker marks them reviewed. The XML sitemap is an index with one file per reviewed language.',
    steps: ['Find the page you need in the list.', 'Open it.', 'Use the XML sitemap only when configuring a crawler.'],
    points: why('the list is generated with the site, not loaded from a sitemap host.'),
    facts: localFacts(
      'Sitemap',
      'A missing translation means it is not reviewed, not that the English page is gone.',
      'Do not submit draft URLs. They are noindex until reviewed.',
      'Open a link and confirm a single H1 that matches the label.',
    ),
    related: ['compress-pdf', 'guides', 'privacy', 'brand', 'tools', 'merge-pdf'],
    intent: 'navigational',
    priority: 3,
    keywords: ['sitemap', 'html sitemap'],
  },
  {
    path: 'guides',
    kind: 'guides',
    h1: 'PDF guides',
    keyword: 'pdf guides',
    description: 'Guides on compressing and keeping PDFs on your device. No upload, and no tracking on these pages.',
    essay: 'Each note answers one question: why a PDF is large, how to shrink it without ruining it, when a black box fails, and how to tell that a tool is uploading. They link to the tool that does the job and say when this version refuses.',
    steps: ['Pick the question that matches the file in front of you.', 'Read the limit before you trust a button.', 'Open the linked tool and keep the file on this device.'],
    points: why('the guides are pages on this site, not embedded players or third-party forms.'),
    facts: localFacts(
      'PDF guides',
      'A guide explains a limit. Reading it does not change your file.',
      'Skip a promise this app has marked as unfinished. The tool page is the authority.',
      'Follow one link, run the tool on a copy, and see whether the note matched the result.',
    ),
    related: guidePaths,
    intent: 'informational',
    priority: 2,
    keywords: ['pdf guides', 'how to compress a pdf'],
  },
];

void brand;
