import { brand, brandName, brandSlug } from '../src/brand';
import { comparePath } from '../src/seo/document';
import { TOOL_SLUG } from '../src/seo/routes';
import { how, localFacts, why, type Seed } from './factory';
import { GUIDES } from './guides';

const guidePaths = GUIDES.map((guide) => `guides/${guide.slug}`);

export const AWAITING_OFFICIAL_SOURCES = [
  'Gmail attachment size — 25 MB ceiling',
  'Outlook attachment size — 20–25 MB limit',
  'WhatsApp document size — 100 MB limit',
  'Job application portal limits — 1–5 MB resume limits',
  'Online form limits — 100 KB, 200 KB, 500 KB, 2 MB ceilings',
];

const privacyCopy: Array<[string, string, string, string]> = [
  ['compress-pdf-without-uploading', 'Compress PDF without uploading', 'compress', 'Compression runs in memory inside this browser tab. The PDF never leaves your device and is never posted to any server API. You can verify this anytime in your browser network log.'],
  ['offline-pdf-tools', 'Offline PDF tools', 'compress', 'All tools work completely offline once loaded. Open the page, turn off Wi-Fi or mobile data, and compress or merge your files with zero internet connection required.'],
  ['merge-pdf-offline', 'Merge PDF offline', 'merge', 'Combine multiple PDF documents directly on your device without an internet connection. Documents remain stored only in your local memory.'],
  ['pdf-tools-no-signup', 'PDF tools with no sign-up', 'compress', 'Free PDF tools with zero registration or email required. No account is needed because no files or personal data are ever retained on remote servers.'],
  ['secure-pdf-compressor', 'Secure PDF compressor', 'compress', 'A private, secure compressor that guarantees confidentiality because files are processed entirely in-browser and never transmitted over the network.'],
  ['pdf-tools-that-work-offline', 'PDF tools that work offline', 'compress', 'Process and compress documents anywhere—on flights, trains, or in locations with spotty reception. All compute is 100% on-device.'],
  ['free-pdf-compressor-no-watermark', 'Free PDF compressor with no watermark', 'compress', 'Compress your documents to exact sizes without watermarks, ads, or hidden paid upgrades. Always free and open source.'],
  ['free-pdf-tools-no-sign-up', 'Free PDF tools with no sign-up', 'compress', 'Open the page, drop your file, and download the result immediately. No sign-ups, subscriptions, or credit cards required.'],
  ['private-pdf-tools', 'Private PDF tool suite', 'compress', 'Private PDF and photo tools running inside your browser. No documents are uploaded to cloud servers or converted by remote workers. Instant local processing with complete privacy.'],
  ['pdf-compressor-offline', 'PDF compressor offline', 'compress', 'An offline PDF compressor that processes documents in client-side memory using WebAssembly. Compress files anywhere without an active internet connection.'],
  ['free-pdf-tools-no-limit', 'Free PDF tools with no limit', 'compress', 'Free PDF tools with no daily file limits, no size caps, and no paid upgrades. Process as many documents as you need directly on your computer or phone.'],
  ['open-source-pdf-tools', 'Open source PDF tools', 'compress', 'Open-source PDF tools with publicly auditable code. Check the client-side architecture yourself on GitHub. No analytics, trackers, or hidden server uploads.'],
  ['local-pdf-tools', 'Local PDF tools', 'compress', 'Local tools that keep every file on your machine. Modern browser-native WebAssembly executes all compression and formatting operations locally.'],
];

export const privacySeeds: Seed[] = privacyCopy.map(([path, h1, toolId, essay]) => ({
  path,
  kind: 'privacy',
  h1,
  keyword: h1.toLowerCase(),
  title: path === 'compress-pdf-without-uploading' ? 'Compress PDF Without Uploading – 100% On-Device | Weesize' : undefined,
  description: path === 'compress-pdf-without-uploading' ? 'Your PDF is compressed inside your browser and never sent anywhere. Works offline. Free, open source, no sign-up.' : `${h1} — no upload. Files stay on this device, and you can turn Wi-Fi off after load to test it.`,
  toolId,
  essay,
  steps: how(h1),
  points: why('the privacy claim is that no upload request exists for the file.'),
  facts: localFacts(
    h1,
    `${h1} runs only the named tool locally. No hidden converters or remote calls exist.`,
    `Zero requests are sent to external servers while using ${h1.toLowerCase()}.`,
    `Check the network panel in Developer Tools when running ${h1.toLowerCase()} to confirm no upload occurs.`,
  ),
  related: ['compress-pdf', 'merge-pdf', 'privacy', 'jpg-to-pdf', 'compress-image', 'signature-resizer'],
  guides: ['guides/is-it-safe-to-upload-pdfs', 'guides/how-to-check-a-tool-does-not-upload', 'guides/offline-pdf-tools'],
  intent: 'commercial',
  priority: 1,
  keywords: [h1.toLowerCase()],
}));

const devices: Array<[string, string, string]> = [
  ['compress-pdf-on-iphone', 'Compress a PDF on iPhone', 'Open this page in Safari on iOS, pick a PDF from Files or iCloud Drive, and compress it locally. The phone never uploads the document to external servers.'],
  ['compress-pdf-on-android', 'Compress a PDF on Android', 'Open this page in Chrome on Android, select your document, and compress to exact KB limits. Processing is 100% on-device and ultra-fast even on budget phones.'],
  ['compress-pdf-on-mac', 'Compress a PDF on Mac', 'Any current Mac browser can run Weesize. Drop the PDF from Finder and get an exact-size compressed copy in seconds without cloud wait times.'],
  ['compress-pdf-on-windows', 'Compress a PDF on Windows', 'Open the page in Edge, Chrome, or Firefox and drop your PDF. Instant client-side compression without installing software or creating accounts.'],
  ['compress-pdf-on-chromebook', 'Compress a PDF on a Chromebook', 'Compress PDFs and images locally on your Chromebook browser. No cloud uploads or extensions required.'],
];

export const deviceSeeds: Seed[] = devices.map(([path, h1, essay]) => ({
  path,
  kind: 'usecase',
  h1,
  keyword: h1.toLowerCase(),
  description: `${h1} in the browser. No upload. Open this page, add the file, and the compressor runs on that device.`,
  toolId: 'compress',
  essay,
  steps: [
    'Open this page on your device.',
    'Add the PDF from local files and select an exact KB size or strength preset.',
    'Download the compressed file directly to your device.',
  ],
  points: why('the same tool runs smoothly across phones and computers with zero cloud dependence.'),
  facts: localFacts(
    h1,
    `${h1} processes the file locally without sending data to any server.`,
    `No app installation or account registration is required for ${h1.toLowerCase()}.`,
    `Test offline by turning on Airplane mode after opening ${h1.toLowerCase()}.`,
  ),
  related: ['compress-pdf', 'compress-pdf-to-100kb', 'compress-pdf-without-uploading', 'jpg-to-pdf', 'offline-pdf-tools'],
  guides: ['guides/compress-a-pdf-on-iphone', 'guides/how-to-check-a-tool-does-not-upload', 'guides/offline-pdf-tools'],
  intent: 'transactional',
  priority: 2,
  keywords: [h1.toLowerCase()],
}));

export const emailSeed: Seed = {
  path: 'compress-pdf-for-email',
  kind: 'usecase',
  h1: 'Compress PDF for email',
  keyword: 'compress pdf for email',
  description: 'Compress a PDF for email in the browser. No upload. Fit Gmail, Outlook, and Yahoo attachment size limits.',
  toolId: 'compress',
  essay:
    'Email services reject oversized attachments (typically 20 MB to 25 MB). Compress your PDF here on your device to shrink images and scanned pages beneath the attachment threshold without cloud links.',
  steps: [
    'Compress your PDF here and pick a size like 1 MB or 2 MB.',
    'Download the compressed file to your device.',
    'Attach directly to your email without triggering cloud storage links.',
  ],
  points: why('shrinking happens before attaching, keeping documents private.'),
  facts: localFacts(
    'Compress PDF for email',
    'Images are compressed to meet email size ceilings while text remains sharp.',
    'Avoid third-party cloud drive links by sending lightweight attachments.',
    'Open the download to verify clarity before sending.',
  ),
  related: ['compress-pdf', 'compress-pdf-to-1mb', 'compress-pdf-to-2mb', 'split-pdf', 'compress-image', 'merge-pdf'],
  guides: ['guides/compress-images-for-email', 'guides/why-is-my-pdf-so-large', 'guides/is-it-safe-to-upload-pdfs'],
  intent: 'transactional',
  priority: 1,
  keywords: ['compress pdf for email', 'reduce pdf for attachment'],
};

export const usecaseSeeds: Seed[] = [
  emailSeed,
  {
    path: 'gmail-attachment-size-limit',
    kind: 'usecase',
    h1: 'Gmail attachment size limit',
    keyword: 'gmail attachment size limit',
    description: 'Gmail attachment size limit guide. Compress PDFs for Gmail attachments locally with no upload. Free, instant, and private.',
    toolId: 'compress',
    essay: 'Gmail enforces a 25 MB total limit for email attachments. If your PDF packet exceeds 25 MB, Gmail uploads it to Google Drive as a shared link. To attach your document directly without cloud links, compress the PDF on your device first. Reducing image resolution and compressing scanned pages brings oversized files under the 25 MB ceiling while keeping text readable.',
    steps: [
      'Compress the PDF here on your device.',
      'Check that the downloaded file is under 25 MB.',
      'Attach it directly in Gmail without converting to a Drive link.',
    ],
    points: why('on-device compression fits Gmail limits before you attach.'),
    facts: localFacts(
      'Gmail attachment size limit',
      'The 25 MB limit is enforced by Gmail. Compressing on your device stays private.',
      'Skip cloud upload prompts by shrinking the file locally.',
      'Check that text remains clear after compression before emailing.',
    ),
    related: ['compress-pdf', 'compress-pdf-for-email', 'compress-pdf-to-5mb', 'split-pdf'],
    guides: ['guides/compress-images-for-email', 'guides/why-is-my-pdf-so-large'],
    intent: 'transactional',
    priority: 2,
    keywords: ['gmail attachment size limit', 'compress pdf for gmail'],
  },
  {
    path: 'outlook-attachment-size-limit',
    kind: 'usecase',
    h1: 'Outlook attachment size limit',
    keyword: 'outlook attachment size limit',
    description: 'Outlook attachment size limit guide. Compress PDFs for Microsoft Outlook attachments on your device. Free, no upload.',
    toolId: 'compress',
    essay: 'Microsoft Outlook limits email attachments to 20 MB or 25 MB depending on server config. When a file is too large, Outlook blocks delivery or prompts for OneDrive. Compressing your PDF locally before attaching keeps the document beneath the threshold without sending files to external sites.',
    steps: [
      'Shrink your PDF locally to under 20 MB.',
      'Attach the compressed copy in Outlook.',
      'Send directly without triggering OneDrive prompts.',
    ],
    points: why('local processing keeps your email attachments private.'),
    facts: localFacts(
      'Outlook attachment size limit',
      'Outlook caps default attachments at 20–25 MB.',
      'Local compression shrinks images inside the PDF without uploading.',
      'Review pages before sending important contracts.',
    ),
    related: ['compress-pdf', 'compress-pdf-for-email', 'compress-pdf-to-2mb'],
    guides: ['guides/compress-images-for-email'],
    intent: 'transactional',
    priority: 2,
    keywords: ['outlook attachment size limit', 'compress pdf for outlook'],
  },
  {
    path: 'whatsapp-pdf-size-limit',
    kind: 'usecase',
    h1: 'WhatsApp PDF size limit',
    keyword: 'whatsapp pdf size limit',
    description: 'WhatsApp PDF size limit guide. Shrink PDFs for mobile messaging directly on your device. Free, no upload.',
    toolId: 'compress',
    essay: 'WhatsApp supports documents up to 100 MB, but large PDFs consume significant mobile data and take longer to transmit over cellular connections. Shrinking your PDF to 1 MB or 2 MB makes sharing fast and light for recipients. Our browser tool processes the file on your smartphone without server uploads.',
    steps: [
      'Compress your PDF to 1 MB or 2 MB on your mobile browser.',
      'Download the compressed PDF to your device.',
      'Share instantly in WhatsApp chats or groups.',
    ],
    points: why('shrinking files on mobile saves cellular data.'),
    facts: localFacts(
      'WhatsApp PDF size limit',
      'Smaller PDFs send faster over mobile network connections.',
      'Compression happens in mobile browser memory.',
      'Keep your original PDF stored locally.',
    ),
    related: ['compress-pdf', 'compress-pdf-on-iphone', 'compress-pdf-on-android'],
    guides: ['guides/compress-a-pdf-on-iphone'],
    intent: 'transactional',
    priority: 2,
    keywords: ['whatsapp pdf size limit', 'reduce pdf size for whatsapp'],
  },
  {
    path: 'compress-pdf-for-job-application',
    kind: 'usecase',
    h1: 'Compress PDF for job application',
    keyword: 'compress pdf for job application',
    description: 'Compress PDF for job applications and resumes – free, no upload. Keep your resume under portal size caps.',
    toolId: 'compress',
    essay: 'Applicant tracking systems (ATS) and job portals cap resume and portfolio uploads between 1 MB and 5 MB. A high-resolution photo or scanned transcript can push a resume over the cap. Compressing your job application PDF locally reduces image size while keeping text crisp for ATS parsers. Because resumes contain sensitive personal data, on-device processing guarantees your information stays private.',
    steps: [
      'Drop your resume or portfolio PDF.',
      'Select a goal like 1 MB or 2 MB.',
      'Download the compressed copy and upload to the job portal.',
    ],
    points: why('on-device compression protects your sensitive resume data.'),
    facts: localFacts(
      'Compress PDF for job application',
      'ATS systems demand sharp text and small file sizes.',
      'Your resume and identity info never touch a server.',
      'Verify formatting and text clarity before applying.',
    ),
    related: ['compress-pdf', 'compress-pdf-to-1mb', 'compress-pdf-to-2mb', 'compress-image'],
    guides: ['guides/shrink-photos-for-applications'],
    intent: 'transactional',
    priority: 2,
    keywords: ['compress pdf for job application', 'reduce resume pdf size'],
  },
  {
    path: 'compress-pdf-for-online-form',
    kind: 'usecase',
    h1: 'Compress PDF for online form',
    keyword: 'compress pdf for online form',
    description: 'Compress PDF for online form submission – free, no upload. Fit strict portal file size requirements on your device.',
    toolId: 'compress',
    essay: 'Government portals, university portals, and tax submission forms enforce strict maximum file upload sizes (such as 100 KB, 500 KB, or 2 MB). Submitting an oversized file causes upload errors or session timeouts. Use our tool to target exact size limits before uploading. Processing runs entirely in your local browser tab, so tax or personal documents are never exposed.',
    steps: [
      'Identify the exact file size limit on the online form.',
      'Select the corresponding exact-size tool target (e.g. 100 KB or 500 KB).',
      'Download and attach the compliant PDF to the form.',
    ],
    points: why('exact size targets help pass strict portal validation.'),
    facts: localFacts(
      'Compress PDF for online form',
      'Online forms reject files exceeding specified kilobyte limits.',
      'Exact-size targets configure compression levels automatically.',
      'Ensure official stamps and seals remain legible.',
    ),
    related: ['compress-pdf', 'compress-pdf-to-100kb', 'compress-pdf-to-500kb', 'signature-resizer'],
    guides: ['guides/shrink-photos-for-applications'],
    intent: 'transactional',
    priority: 2,
    keywords: ['compress pdf for online form', 'reduce pdf size for upload'],
  },
  {
    path: 'reduce-photo-size-for-online-application',
    kind: 'usecase',
    h1: 'Reduce photo size for online application',
    keyword: 'reduce photo size for online application',
    description: 'Reduce photo size for online applications – free, no upload. Resize passport photos, identity scans, and headshots.',
    toolId: 'compress-images',
    essay: 'Online identity verification and application forms often require passport photos or headshots under 20 KB, 50 KB, or 100 KB. High-resolution smartphone photos are 3 MB to 10 MB. This tool resizes image dimensions and compresses JPG/PNG files locally to meet strict size caps without sending your identity photograph to external servers.',
    steps: [
      'Choose the image file and set the required target size (e.g. 50 KB).',
      'The browser resizes dimensions and encodes the image locally.',
      'Download and upload the compliant photo to your application.',
    ],
    points: why('identity photos stay safe when compressed on your device.'),
    facts: localFacts(
      'Reduce photo size for online application',
      'Application portals require small photo dimensions and byte limits.',
      'Processing removes EXIF camera location metadata automatically.',
      'Verify photo clarity and facial details at 100% zoom.',
    ),
    related: ['compress-image', 'compress-image-to-50kb', 'compress-jpg-to-100kb', 'jpg-to-pdf', 'signature-resizer', 'id-photo'],
    guides: ['guides/shrink-photos-for-applications', 'guides/best-image-format-for-the-web'],
    intent: 'transactional',
    priority: 2,
    keywords: ['reduce photo size for online application', 'compress photo to 50kb for form'],
  },
];

const converts: Array<[string, string, NonNullable<Seed['presetMime']>, string, string]> = [
  ['heic-to-jpg', 'HEIC to JPG', 'image/jpeg', 'heic to jpg', 'Convert iPhone camera HEIC photos to standard JPEG directly in your browser. Fast, batch-ready, and 100% private.'],
  ['webp-to-jpg', 'WebP to JPG', 'image/jpeg', 'webp to jpg', 'Convert WebP images to universal JPG format for portals that reject WebP files. Processed locally in seconds.'],
  ['png-to-jpg', 'PNG to JPG', 'image/jpeg', 'png to jpg', 'Convert heavy PNG photos and scans to lightweight JPG format. Reduces file size significantly.'],
  ['jpg-to-png', 'JPG to PNG', 'image/png', 'jpg to png', 'Convert JPG photos to PNG format locally in your browser with zero upload.'],
  ['webp-to-png', 'WebP to PNG', 'image/png', 'webp to png', 'Convert WebP files to standard PNG format without uploading to any server.'],
  ['avif-to-jpg', 'AVIF to JPG', 'image/jpeg', 'avif to jpg', 'Convert modern AVIF images into standard JPEG format directly on your device.'],
  ['jpg-to-webp', 'JPG to WebP', 'image/webp', 'jpg to webp', 'Convert JPG images to modern WebP format for faster web performance.'],
];

export const convertSeeds: Seed[] = converts.map(([path, h1, mime, keyword, essay]) => ({
  path,
  kind: 'convert',
  h1,
  keyword,
  title: path === 'heic-to-jpg' ? 'HEIC to JPG – Free, Instant, No Upload | Weesize' : `${h1} – Free, Instant, No Upload | Weesize`,
  description: path === 'heic-to-jpg' ? 'Convert iPhone HEIC photos to JPG in your browser. Batch convert, keep quality, strip location data. Free and private.' : `${h1} in your browser with no upload. Encoded on your device with complete privacy.`,
  toolId: 'compress-images',
  presetMime: mime,
  essay,
  steps: [
    `Drop your photo or screenshot.`,
    'The browser decodes and converts the image locally in memory.',
    'Download your new converted image immediately.',
  ],
  points: why(`the ${h1} conversion uses browser-native canvas APIs with zero server calls.`),
  facts: localFacts(
    h1,
    `${h1} re-encodes image pixels in your chosen output format locally.`,
    `Privacy is maintained for ${h1.toLowerCase()} because image bytes never leave your device.`,
    `Verify downloaded ${h1.toLowerCase()} image quality before submitting.`,
  ),
  related: ['compress-image', 'jpg-to-pdf', 'compress-pdf', 'signature-resizer'],
  neighbors: converts.map(([item]) => item).filter((item) => item !== path),
  guides: ['guides/best-image-format-for-the-web', 'guides/heic-photos-on-windows', 'guides/shrink-photos-for-applications'],
  intent: 'transactional',
  priority: 1,
  keywords: [keyword],
}));

const rivals: Array<[string, string, string, string]> = [
  ['ilovepdf', 'iLovePDF', 'iLovePDF is a widely used web PDF suite that processes files on remote cloud servers.', 'Weesize focuses on exact file size compression and photo resizing with 100% on-device processing. No files are uploaded and no accounts are required.'],
  ['smallpdf', 'Smallpdf', 'Smallpdf offers cloud-based PDF conversion with daily free limits.', 'Weesize processes documents in your browser with zero uploads, no daily task limits, and exact KB targeting for forms.'],
  ['adobe-acrobat-online', 'Adobe Acrobat online', 'Adobe Acrobat online provides cloud-hosted PDF tools requiring Adobe accounts.', 'Weesize provides fast, private on-device compression and resizing without account creation.'],
  ['pdf24', 'PDF24', 'PDF24 offers online and desktop PDF utilities.', 'Weesize runs instantly inside any modern browser on desktop or phone without installing software.'],
  ['sejda', 'Sejda', 'Sejda provides web PDF editing with hourly limits.', 'Weesize provides unlimited on-device compression and image tools with zero server transmission.'],
];

export const compareSeeds: Seed[] = rivals.flatMap(([slug, name, good, rest]) => {
  const related = ['compress-pdf', 'merge-pdf', 'split-pdf', 'privacy', 'jpg-to-pdf', 'compress-image'];
  const guides = ['guides/is-it-safe-to-upload-pdfs', 'guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/how-to-check-a-tool-does-not-upload'];
  const alt: Seed = {
    path: `alternatives/${slug}`,
    kind: 'compare',
    h1: `${name} alternative`,
    keyword: `free ${name.toLowerCase()} alternative`,
    title: slug === 'ilovepdf' ? `Free ${name} Alternative, No Upload | ${brandName()}` : undefined,
    description: slug === 'ilovepdf' ? `Looking for an ${name} alternative? ${brandName()} is free, open source, and processes files on your device with no upload, no ads, and no limits.` : `Free ${name} alternative with no upload and no sign-up. Files stay private on your device. Compare features and architecture.`,
    essay: `${good} ${rest}`,
    steps: [
      'Choose whether your file can leave your device. For sensitive personal data, use a local tool.',
      `Use ${brandName()} for exact-size compression, signatures, ID photos, and PDF organizing.`,
      `For advanced desktop publishing, use dedicated local software like BentoPDF.`,
    ],
    points: [
      'Zero uploads: files are processed in local memory.',
      'Exact size target slider: hit specific KB limits required by online forms.',
      'Free forever with no accounts, ads, or daily task caps.',
    ],
    facts: localFacts(
      `${name} alternative`,
      `${brandName()} executes all compression and conversion on your device instead of ${name}.`,
      `No trackers, analytics pixels, or cookies are loaded on the ${name} alternative page.`,
      `Test offline functionality on ${name} alternative by turning off Wi-Fi after page load.`,
    ),
    related,
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: [`${name.toLowerCase()} alternative`, `${brandSlug()} vs ${slug}`],
  };
  const versus: Seed = {
    ...alt,
    path: comparePath(slug),
    h1: `${brandName()} vs ${name}`,
    keyword: `${brandName().toLowerCase()} vs ${name.toLowerCase()}`,
    title: slug === 'ilovepdf' ? `${brandName()} vs ${name} – Direct Comparison | ${brandName()}` : undefined,
    description: slug === 'ilovepdf' ? `Weesize vs iLovePDF: compare client-side processing, zero uploads, exact size targeting, and privacy. Free forever with no accounts or limits.` : `${brandName()} vs ${name}: local tools, no upload, and zero cloud tracking. Compare features and privacy architecture.`,
    essay: `${brandName()} keeps files on your device and optimizes for exact form requirements. ${name} processes files on cloud servers. ${good} ${rest}`,
    facts: localFacts(
      `${brandName()} vs ${name}`,
      `The key architectural difference between ${brandName()} and ${name} is where files are processed. ${brandName()} never sends files across the network.`,
      `Weesize provides exact KB target controls tailored for portal uploads when compared to ${name}.`,
      `All features in ${brandName()} remain free and unlimited without account registration when evaluated alongside ${name}.`,
    ),
  };
  return [alt, versus];
});

export const guideSeeds: Seed[] = GUIDES.map((guide) => ({
  path: `guides/${guide.slug}`,
  kind: 'guide' as const,
  h1: guide.h1,
  keyword: guide.keyword,
  description: guide.description,
  essay: guide.essay,
  steps: guide.steps,
  points: guide.points,
  facts: guide.facts,
  related: guide.related,
  intent: 'informational',
  priority: 2,
  keywords: [guide.keyword],
}));

export const frameSeeds: Seed[] = [
  {
    path: 'about',
    kind: 'legal',
    h1: `About ${brandName()}`,
    keyword: `about ${brandName().toLowerCase()}`,
    description: 'Weesize is a free, open-source tool that compresses photos, signatures and PDFs to an exact file size in your browser, without uploading files.',
    essay: `Weesize is a free, open-source tool that compresses photos, signatures and PDFs to an exact file size in your browser, without uploading files.

Weesize is built for students and job applicants resizing photos, signatures and PDFs for online forms, as well as anyone who wants private file compression without uploading files to remote servers.

How is Weesize different?
Weesize does one job better than anyone: gets any photo, signature or PDF to the exact size a form needs. It is not a 100-tool PDF suite; for full PDF page editing and document creation, we warmly recommend BentoPDF. Weesize focuses entirely on exact size targeting, background cleaning, and fast on-device performance.

All processing runs directly in your browser using modern WebAssembly and JavaScript engines under the permissive MIT license. Once the web application loads, you can turn off Wi-Fi or disconnect from the internet completely and continue using all features offline.

Connect with our project on GitHub (https://github.com/Ansochacko/weesize) and Instagram (https://www.instagram.com/weesize).`,
    steps: [
      'Load the application in any modern desktop or mobile browser.',
      'Select any exact size photo, signature, or PDF tool.',
      'Process your files locally and download results with zero upload.',
    ],
    points: [
      '100% on-device processing via browser WebAssembly and Web APIs.',
      'Open source repository on GitHub under the MIT license.',
      'Zero server uploads, zero sign-ups, zero tracking scripts, and zero ads.',
    ],
    facts: localFacts(
      `About ${brandName()}`,
      `${brandName()} processes every file in client-side memory without external API calls.`,
      `You can inspect network traffic in Developer Tools to confirm zero upload requests occur.`,
      `The product is free forever under the MIT license.`,
    ),
    related: ['privacy', 'compress-pdf-without-uploading', 'offline-pdf-tools', 'compress-pdf', 'compress-image', 'signature-resizer', 'tools', 'brand'],
    guides: ['guides/is-it-safe-to-upload-pdfs', 'guides/how-to-check-a-tool-does-not-upload', 'guides/what-a-browser-pdf-tool-can-and-cannot-do'],
    intent: 'informational',
    priority: 1,
    keywords: [`about ${brandName().toLowerCase()}`, 'open source pdf tools', 'exact file size compressor'],
  },
  {
    path: '',
    kind: 'home',
    h1: 'Get any photo, signature or PDF to the exact size a form needs.',
    keyword: 'compress photo signature pdf to exact size',
    title: 'Get Any Photo, Signature or PDF to Exact Size — Weesize',
    description: 'Free, private and fast. Pick a size, drop your file, done. Nothing is uploaded.',
    essay: `Weesize gets any photo, signature or PDF to the exact size a form needs. Free, private and fast. Pick a size, drop your file, done. Nothing is uploaded.`,
    steps: how('The home page'),
    points: why('the home page is the app, not a funnel into an account.'),
    facts: localFacts(
      'Weesize',
      'All processing executes on your device in browser memory.',
      'Zero files leave your computer or phone.',
      'Fast, offline-ready, and free under the MIT license.',
    ),
    related: ['compress-pdf', 'compress-image', 'signature-resizer', 'id-photo', 'merge-pdf', 'split-pdf', 'jpg-to-pdf', 'pdf-to-jpg', 'get-it-accepted', 'privacy', 'brand'],
    intent: 'navigational',
    priority: 1,
    keywords: ['weesize', 'compress photo to size', 'signature resizer', 'compress pdf to exact size'],
  },
  {
    path: 'tools',
    kind: 'tools',
    h1: 'All tools',
    keyword: 'pdf and photo tools',
    description: 'Explore all photo, signature, and PDF tools in Weesize. Free, private, and 100% on-device.',
    essay: 'Browse our complete suite of photo, signature, and PDF tools. Every tool runs entirely inside your browser using client-side WebAssembly with complete privacy and zero file uploads.',
    steps: ['Select a tool from the catalog or search using ⌘K.', 'Drop your file and set your target specifications.', 'Download your processed file instantly with zero upload.'],
    points: why('every tool runs locally on your computer or phone without contacting an external server.'),
    facts: localFacts(
      'All tools',
      'Using any tool is completely free with no account or sign-in needed.',
      'All tools process files locally and work even offline.',
      'No files or personal data ever touch a remote server.',
    ),
    related: Object.values(TOOL_SLUG),
    intent: 'navigational',
    priority: 1,
    keywords: ['pdf tools', 'photo tools', 'all weesize tools'],
  },
  {
    path: 'privacy',
    kind: 'privacy',
    h1: 'Privacy',
    keyword: 'pdf privacy',
    description: 'Weesize privacy: processed on your device with zero uploads, zero trackers, and 100% open source under the MIT license.',
    toolId: 'compress',
    essay:
      'Files you open are handled entirely in your local browser tab using JavaScript and WebAssembly. They are never posted to an API, never sent across the network, and never written into server storage. This website loads zero analytics scripts, zero advertising trackers, and zero session recorders. You can verify this anytime by opening Developer Tools Network tab. Every tool is free forever under the MIT license.',
    steps: ['Drop any confidential document or photo.', 'Processing runs locally in memory.', 'Download your file with complete peace of mind.'],
    points: why('privacy is guaranteed by design because no upload mechanism exists.'),
    facts: localFacts(
      'Privacy',
      'No files or telemetry are transmitted to any server.',
      'Disconnect from the internet after load and the app continues working completely.',
      'Full source code is open and verifiable on GitHub.',
    ),
    related: ['compress-pdf-without-uploading', 'offline-pdf-tools', 'pdf-tools-no-signup', 'brand', 'compress-pdf', 'guides'],
    guides: ['guides/is-it-safe-to-upload-pdfs', 'guides/how-to-check-a-tool-does-not-upload', 'guides/offline-pdf-tools'],
    intent: 'informational',
    priority: 1,
    keywords: ['pdf privacy', 'no upload pdf compressor', 'private photo resizer'],
  },
  {
    path: 'brand',
    kind: 'brand',
    h1: `${brandName()} brand`,
    keyword: `${brandName().toLowerCase()} logo`,
    description: `Free ${brandName()} logo, marks, and colors. Download brand assets and view guidelines.`,
    essay: `${brandName()}’s mark is a large faint page with a smaller solid page inside it: a big file becomes a wee file. Download official SVG and PNG assets for press and community references.`,
    steps: ['Download the official SVG or PNG asset.', 'Maintain clear space around the logo.', 'Use colors specified in the guidelines.'],
    points: ['Use vector SVG files where possible.', 'Primary accent color is #2340C9.', 'Wordmark uses lowercase IBM Plex Sans SemiBold.'],
    facts: localFacts(
      `${brandName()} brand`,
      'The logo shapes represent file compression from large to wee size.',
      'Official brand assets are available under permissive licenses.',
      'Do not distort or recolor the brand mark.',
    ),
    related: ['press', 'privacy', 'compress-pdf', 'guides', 'sitemap', 'tools'],
    intent: 'navigational',
    priority: 3,
    keywords: [`${brandName().toLowerCase()} logo`, `${brandName().toLowerCase()} brand`],
  },
  {
    path: 'press',
    kind: 'press',
    h1: 'Press',
    keyword: 'press kit',
    description: `Press notes and media information for ${brandName()}. Free, private, open-source file compression.`,
    essay: `${brand.tagline} ${brandName()} is a client-side web application for people who need exact file sizes for online forms and will not upload sensitive personal documents to remote cloud servers. Free, open source under the MIT license, and runs on any device.`,
    steps: ['Download brand marks from the brand page.', 'Test offline functionality directly in your browser.', 'Reference public code on GitHub.'],
    points: ['Tagline: "Get any photo, signature or PDF to the exact size a form needs."', 'Open source on GitHub with zero telemetry.', 'Processed 100% on-device.'],
    facts: localFacts(
      'Press',
      'Weesize is free and open source under the MIT license.',
      'All processing runs client-side in the browser.',
      'Verify the offline test anytime.',
    ),
    related: ['brand', 'privacy', 'compress-pdf', 'guides/is-it-safe-to-upload-pdfs', 'sitemap', 'tools'],
    intent: 'navigational',
    priority: 3,
    keywords: [`${brandName().toLowerCase()} press`, 'weesize press kit'],
  },
  {
    path: 'sitemap',
    kind: 'sitemap',
    h1: 'Sitemap',
    keyword: 'sitemap',
    description: `Free HTML sitemap of ${brandName()} working pages and tools.`,
    essay: 'Explore all working tools, exact-size target pages, format converters, use cases, and guides available on Weesize.',
    steps: ['Find your required tool or guide.', 'Open the page to start working locally.', 'All linked tools run in-browser.'],
    points: why('all indexable pages are listed clearly for users and search engines.'),
    facts: localFacts(
      'Sitemap',
      'Lists only active, working tools and indexable guides.',
      'All pages load cleanly with prerendered content.',
      'Check the XML sitemap for automated index crawlers.',
    ),
    related: ['compress-pdf', 'compress-image', 'signature-resizer', 'id-photo', 'guides', 'privacy', 'tools'],
    intent: 'navigational',
    priority: 3,
    keywords: ['sitemap', 'html sitemap', 'weesize sitemap'],
  },
  {
    path: 'guides',
    kind: 'guides',
    h1: 'Guides',
    keyword: 'pdf and image guides',
    description: 'Guides on resizing photos, signatures, and PDFs for online applications and forms without uploading.',
    essay: 'Practical guides answering common questions: how to shrink photos and signatures for job and exam applications, how to fit email limits, and how on-device privacy works.',
    steps: ['Select a guide matching your task.', 'Follow the quick steps.', 'Open the corresponding tool to complete your task locally.'],
    points: why('guides provide clear, helpful instructions without marketing filler.'),
    facts: localFacts(
      'Guides',
      'Guides explain practical file sizing and formatting techniques.',
      'All companion tools run directly on your device.',
      'Zero ads or trackers across all guide pages.',
    ),
    related: guidePaths,
    intent: 'informational',
    priority: 2,
    keywords: ['pdf guides', 'photo resize guides', 'form upload guides'],
  },
];
