import { how, localFacts, why, type Seed } from './factory';
import { IMAGE_SIZE_SLUGS, PDF_SIZE_SLUGS } from '../src/seo/routes';

export const toolSeeds: Seed[] = [
  {
    path: 'compress-pdf',
    kind: 'tool',
    h1: 'Compress PDF',
    keyword: 'compress pdf',
    title: 'Compress PDF – Pick an Exact Size, Free | Weesize',
    description: 'Compress PDF to an exact KB or MB target. Free, unlimited, and 100% private: files stay on your device with no upload. Drop your PDF to shrink.',
    toolId: 'compress',
    essay:
      'Compress PDF when photos or scans inside the file are heavier than they need to be. Light keeps more detail, Recommended is the usual pass, and Strong pushes scans down further. Text drawing commands stay text. A typed contract often shrinks only a little, because the words were already efficient. A scanned packet can shrink a lot. This screen does not promise an exact byte count; the size pages set a goal and still refuse to invent a size the pictures cannot reach. If nothing smaller is possible, you get the original back and a plain sentence that says so.',
    steps: how('Compress PDF'),
    points: why('the PDF is read in memory and is never posted to a server.'),
    facts: localFacts(
      'Compress PDF',
      'Images may be resized and re-encoded. Text stays text. The new file replaces the old one only when it is smaller.',
      'Do not use Compress PDF to hide a sentence. Shrinking a page is not redaction.',
      'Open the download and read a paragraph and a photo. If the type broke, step back one strength.',
    ),
    related: ['merge-pdf', 'split-pdf', 'compress-image', 'pdf-to-jpg', 'repair-pdf', 'organize-pdf'],
    neighbors: PDF_SIZE_SLUGS,
    guides: ['guides/why-is-my-pdf-so-large', 'guides/reduce-pdf-size-without-losing-quality', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor'],
  },
  {
    path: 'merge-pdf',
    kind: 'tool',
    h1: 'Merge PDF',
    keyword: 'merge pdf',
    title: 'Merge PDF – Combine Files Free, No Upload | Weesize',
    description: 'Combine multiple PDFs into one document in seconds. Free, unlimited, and 100% private with no upload or sign-up. Drop your files to merge now.',
    toolId: 'merge',
    essay:
      'Merge PDF when a cover letter, a form, and a scan belong in one packet. Drag the rows until the order matches the story a reader should see. The combined file is built here from the pages you supplied. It does not retype them and it does not send them out to be stitched. The app warns above 150 MB instead of pretending a laptop is a server. A locked file has to be unlocked on this device first. The merger will not guess the password.',
    steps: how('Merge PDF'),
    points: why('every source PDF stays on this device while the pages are copied into one file.'),
    facts: localFacts(
      'Merge PDF',
      'Pages are copied in the order you leave on screen. Dragging a row changes that order before anything is written.',
      'Do not merge two drafts if you still need to see what changed. Combining them is not a comparison.',
      'Check the first and last page of the download against your list. A locked file is reported, not silently dropped.',
    ),
    related: ['compress-pdf', 'organize-pdf', 'split-pdf', 'jpg-to-pdf', 'add-page-numbers-to-pdf', 'watermark-pdf'],
    guides: ['guides/merge-pdfs-without-an-account', 'guides/organize-pages-before-you-send', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['merge pdf', 'combine pdf'],
  },
  {
    path: 'split-pdf',
    kind: 'tool',
    h1: 'Split PDF',
    keyword: 'split pdf',
    title: 'Split PDF – Extract Pages Free, No Upload | Weesize',
    description: 'Extract pages or page ranges from any PDF instantly. Free, unlimited, and 100% private with no upload or sign-up. Select your PDF to split.',
    toolId: 'split',
    essay:
      'Split PDF when one file holds pieces that should travel separately: a signed page, an appendix, or one invoice from a statement. You name the pages or a range. The download contains those pages and not the rest. Splitting does not compress artwork and does not OCR a scan. A confidential page you leave out never sits on someone else’s disk as part of processing. If you need a new order rather than a cut, use Organize PDF.',
    steps: how('Split PDF'),
    points: why('only the pages you keep are written, and the source never leaves this device.'),
    facts: localFacts(
      'Split PDF',
      'The new file contains the ranges you asked for. Other pages are not in the download.',
      'Splitting does not hide a sentence on a page you keep. It only omits pages you did not ask for.',
      'Count the pages in the download against the range you typed. The file name follows that range.',
    ),
    related: ['merge-pdf', 'organize-pdf', 'compress-pdf', 'rotate-pdf', 'pdf-to-jpg', 'repair-pdf'],
    guides: ['guides/split-a-pdf-by-page-range', 'guides/organize-pages-before-you-send', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['split pdf', 'extract pdf pages'],
  },
  {
    path: 'organize-pdf',
    kind: 'tool',
    h1: 'Organize PDF',
    keyword: 'organize pdf',
    title: 'Organize PDF – Reorder & Rotate Pages Free | Weesize',
    description: 'Reorder, rotate, and delete PDF pages right in your browser. Free, unlimited, and 100% private with no upload. Arrange your document now.',
    toolId: 'organize',
    essay:
      'Organize PDF when the pages arrived in the wrong order or a blank slipped in. Drag one page, or several, until the sequence is right. Delete means that page is left out of the download. Rotate on the grid fixes a single sideways page; Rotate PDF is the separate tool when the whole packet faces the same wrong way. Undo lasts while the tab is open. The saved file follows the order on screen.',
    steps: how('Organize PDF'),
    points: why('thumbnails are drawn here, so arranging a contract does not require an account.'),
    facts: localFacts(
      'Organize PDF',
      'The download follows the on-screen order. Deleted pages are omitted. A group of selected pages keeps its relative order.',
      'Deleting a page is not redaction of a sentence on a page you keep.',
      'Match the position numbers to the story you want, then confirm the first page of the download.',
    ),
    related: ['merge-pdf', 'split-pdf', 'rotate-pdf', 'compress-pdf', 'add-page-numbers-to-pdf', 'crop-pdf'],
    guides: ['guides/organize-pages-before-you-send', 'guides/merge-pdfs-without-an-account', 'guides/split-a-pdf-by-page-range'],
    intent: 'transactional',
    priority: 1,
    keywords: ['organize pdf', 'reorder pdf pages'],
  },
  {
    path: 'rotate-pdf',
    kind: 'tool',
    h1: 'Rotate PDF',
    keyword: 'rotate pdf',
    title: 'Rotate PDF – Turn PDF Pages Free, No Upload | Weesize',
    description: 'Rotate PDF pages permanently in your browser. Free, instant, and 100% private with no upload: files stay on your device. Turn your PDF now.',
    toolId: 'rotate',
    essay:
      'Rotate PDF turns every page by the same quarter turn. Use it when a whole scan was fed through sideways. When only one page is sideways, use the grid in Organize PDF instead. The rotation is written on this device. The rotate action itself does not recompress the pictures.',
    steps: how('Rotate PDF'),
    points: why('rotation changes the page boxes on this device, not a job queued on a server.'),
    facts: localFacts(
      'Rotate PDF',
      'Every page receives the same quarter turn in this version. Mixed orientations need Organize PDF.',
      'Rotating does not shrink the file and does not make a scan searchable.',
      'Open the download and check that a heading reads left to right.',
    ),
    related: ['organize-pdf', 'crop-pdf', 'compress-pdf', 'scan-to-pdf', 'merge-pdf', 'split-pdf'],
    guides: ['guides/organize-pages-before-you-send', 'guides/compress-a-pdf-on-iphone', 'guides/why-is-my-pdf-so-large'],
    intent: 'transactional',
    priority: 2,
    keywords: ['rotate pdf', 'turn pdf pages'],
  },
  {
    path: 'crop-pdf',
    kind: 'tool',
    h1: 'Crop PDF',
    keyword: 'crop pdf',
    title: 'Crop PDF – Trim PDF Margins Free, No Upload | Weesize',
    description: 'Trim unwanted margins from scanned PDFs in your browser. Free, instant, and 100% private with no upload: files stay on your device. Crop now.',
    toolId: 'crop',
    essay:
      'Crop PDF trims the same margin, in points, from every page. Use it for a wide dark scanner border or a slide exported with an empty frame. This version does not offer a dragged box per page. Cropping changes the visible box. It is not a promise that cropped-away text is gone the way true redaction would remove it. Do not crop to hide an account number.',
    steps: how('Crop PDF'),
    points: why('the crop box is applied in this browser, so a bordered scan is not posted.'),
    facts: localFacts(
      'Crop PDF',
      'The same inset is used on every page. Content outside that box leaves the visible page.',
      'A crop is the wrong way to hide confidential text. This version does not claim to redact.',
      'Look at the edges of the download. Headings should not be sliced.',
    ),
    related: ['rotate-pdf', 'organize-pdf', 'compress-pdf', 'redact-pdf', 'scan-to-pdf', 'watermark-pdf'],
    guides: ['guides/how-to-redact-a-pdf-properly', 'guides/organize-pages-before-you-send', 'guides/why-is-my-pdf-so-large'],
    intent: 'transactional',
    priority: 2,
    keywords: ['crop pdf', 'trim pdf margins'],
  },
  {
    path: 'jpg-to-pdf',
    kind: 'tool',
    h1: 'JPG to PDF',
    keyword: 'jpg to pdf',
    title: 'JPG to PDF – Convert Photos Free, No Upload | Weesize',
    description: 'Convert JPG, PNG, and WebP photos into one clean PDF. Free, instant, and 100% private with no upload or watermarks. Select your photos now.',
    toolId: 'images',
    essay:
      'JPG to PDF builds one PDF from photos and screenshots you already have. Drag them into reading order. Reducing file size is on by default so a phone photo does not become an enormous page. Pictures are not uploaded to a converter. PNG and WebP can sit in the same packet when the browser can decode them. HEIC depends on that same browser support; no HEIC library is bundled.',
    steps: how('JPG to PDF'),
    points: why('photos become pages here, without a conversion service.'),
    facts: localFacts(
      'JPG to PDF',
      'Each image becomes a page, in the order shown. Large photos can be reduced before they are placed.',
      'This does not straighten a page or run OCR. It only builds a PDF from the pictures.',
      'Flip through the PDF. The order should match the list, and text in a screenshot should still be readable.',
    ),
    related: ['compress-image', 'scan-to-pdf', 'merge-pdf', 'compress-pdf', 'pdf-to-jpg', 'png-to-jpg'],
    guides: ['guides/turn-photos-into-a-pdf', 'guides/shrink-photos-for-applications', 'guides/best-image-format-for-the-web'],
    intent: 'transactional',
    priority: 1,
    keywords: ['jpg to pdf', 'jpeg to pdf', 'photos to pdf'],
  },
  {
    path: 'pdf-to-jpg',
    kind: 'tool',
    h1: 'PDF to JPG',
    keyword: 'pdf to jpg',
    title: 'PDF to JPG – Extract Pages as Images Free | Weesize',
    description: 'Save PDF pages as high-quality JPG images in your browser. Free, instant, and 100% private with no upload: files stay local. Convert pages now.',
    toolId: 'pdf-images',
    essay:
      'PDF to JPG renders each page to a JPEG here. Use it when a form only accepts images. A unusual font may substitute. The JPEG is a picture, so the text is no longer selectable. Several pages download as a zip. This is an export, not compression of the PDF. If you wanted a smaller PDF, use Compress PDF.',
    steps: how('PDF to JPG'),
    points: why('pages are rasterized locally, so a statement does not go to an image host.'),
    facts: localFacts(
      'PDF to JPG',
      'You get one JPEG per page. Multiple pages arrive in a zip. The words in the JPEG are pixels.',
      'Keep the PDF if you still need to search or copy the words. The JPEG cannot do that.',
      'Open a JPEG and check small type. This export is for viewing, not for a print plate.',
    ),
    related: ['compress-pdf', 'jpg-to-pdf', 'pdf-to-word', 'split-pdf', 'compress-image', 'png-to-jpg'],
    guides: ['guides/best-image-format-for-the-web', 'guides/why-is-my-pdf-so-large', 'guides/turn-photos-into-a-pdf'],
    intent: 'transactional',
    priority: 1,
    keywords: ['pdf to jpg', 'pdf to jpeg'],
  },
  {
    path: 'pdf-to-word',
    kind: 'tool',
    h1: 'PDF to Word',
    keyword: 'pdf to word',
    title: 'PDF to Word – Convert PDF to DOCX Free | Weesize',
    description: 'Extract text from PDFs into editable Word documents. Free, fast, and 100% private: files stay on your device with no upload. Convert now.',
    toolId: 'pdf-word',
    essay:
      'PDF to Word pulls text the PDF already contains into a simple document. It does not reconstruct columns or a designer’s layout, and it will not invent words that were never in a text layer. A scan without OCR stays nearly empty, because a picture of a letter is not text. That limit is stated so you do not download a blank file and assume an upload-based tool is “just better” without noticing it sent the file away.',
    steps: how('PDF to Word'),
    points: why('text extraction stays on this device, and missing text is not filled by a cloud model.'),
    facts: localFacts(
      'PDF to Word',
      'You get the text layer in a simple Word file. Columns and exact spacing are not reproduced.',
      'A photographed scan will not become a Word document here. This version does not fake OCR.',
      'Copy a sentence from the PDF and find it in the download. If it is missing, it was not real text.',
    ),
    related: ['word-to-pdf', 'pdf-to-markdown', 'ocr-pdf', 'compress-pdf', 'compare-pdf', 'pdf-to-excel'],
    guides: ['guides/pdf-to-word-what-you-keep', 'guides/make-a-scanned-pdf-searchable', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['pdf to word', 'pdf to docx'],
  },
  {
    path: 'word-to-pdf',
    kind: 'tool',
    h1: 'Word to PDF',
    keyword: 'word to pdf',
    title: 'Word to PDF – Convert DOCX Free, No Upload | Weesize',
    description: 'Turn Word documents into clean PDFs right in your browser. Free, unlimited, and 100% private: no upload or sign-up. Select your file now.',
    toolId: 'word',
    essay:
      'Word to PDF reads a .docx locally and writes a PDF of its paragraphs. Complex layouts may shift. This beta does not claim pixel-perfect Word. It also refuses to fetch a document from a web address, because that request would leave the device. When letterhead must match to the millimetre, export from the editor that built the file. Use this page when you want a simple PDF and you do not want to hand the draft to a conversion site.',
    steps: how('Word to PDF'),
    points: why('the docx is unzipped and read in this browser, not posted to a converter.'),
    facts: localFacts(
      'Word to PDF',
      'Paragraphs become PDF text. Elaborate layouts can move, and the page says so before you rely on it.',
      'Do not paste a web address. This app will not fetch a page from the internet to turn it into a PDF.',
      'Read the download next to the original. If a table broke, use the editor’s own export for that file.',
    ),
    related: ['pdf-to-word', 'html-to-pdf', 'merge-pdf', 'compress-pdf', 'jpg-to-pdf', 'excel-to-pdf'],
    guides: ['guides/word-to-pdf-what-changes', 'guides/html-to-pdf-without-fetching-the-web', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['word to pdf', 'docx to pdf'],
  },
];

void IMAGE_SIZE_SLUGS;
