import { how, localFacts, why, type Seed } from './factory';
import { brandName } from '../src/brand';

const guides = ['guides/is-it-safe-to-upload-pdfs'];

export const toolSeedsC: Seed[] = [
  {
    path: 'get-it-accepted',
    kind: 'tool',
    h1: 'Get it accepted',
    keyword: 'pdf upload requirements',
    description: 'Check a file against a verified portal rule with no upload. Unpublished drafts are never applied.',
    toolId: 'presets',
    essay:
      'Get it accepted lists only requirements a person copied from an official page, with the source URL and the day they were checked. Five example records ship as drafts with the word PLACEHOLDER in the notes. Those records stay out of this page, the search, and the sitemap, because a guessed passport rule would be worse than no rule. When a verified record exists, the checklist marks each limit met, not met, or not checked. Head size and background color are not checked by a model in this version. Report outdated opens your mail or a GitHub issue. This app does not send that report.',
    steps: how('Get it accepted'),
    points: why('a rule is applied only after it is marked verified from an official page.'),
    facts: localFacts(
      'Get it accepted',
      'You see a checklist. A draft preset is refused. Missing official numbers stay blank instead of being filled in.',
      'Do not treat Exampleland placeholders as a visa or passport rule. They are schema samples.',
      'Read the source link and the last-checked date before you trust a green mark.',
    ),
    related: ['id-photo', 'compress-pdf', 'check-pdf-before-sending', 'privacy', 'compress-image', 'guides'],
    guides,
    intent: 'informational',
    priority: 2,
    keywords: ['pdf upload requirements', 'get a pdf accepted'],
  },
  {
    path: 'id-photo',
    kind: 'tool',
    h1: 'ID photo',
    keyword: 'id photo maker',
    description: 'Crop an ID photo to exact pixels in the browser. No upload and no face retouching.',
    toolId: 'id-photo',
    essay:
      'ID photo makes a center crop at the pixel size you type and can lay copies on a 4 by 6 inch sheet with cut marks. The pixels inside the crop are copied. There is no smoothing, reshaping, or lighting effect. Face position, head size, and whether the eyes are open are listed as not checked, because no face detector ships in this version. A MediaPipe model would have to be stored with the app. It is not. Background replacement stays off, including when a future preset forbids an edited background. Some offices reject a replaced background even when a tool can paint one. Compare the crop with the official example yourself.',
    steps: how('ID photo'),
    points: why('the crop is a copy of the pixels you already have, with no portrait filter.'),
    facts: localFacts(
      'ID photo',
      'You get a centered crop and an optional print sheet. The face is not beautified. Corners are compared only as a color hint.',
      'Do not use this when the office forbids any crop or any software processing. Read their page.',
      'Measure the downloaded image. The pixel width and height should match the numbers you typed.',
    ),
    related: ['get-it-accepted', 'compress-image', 'jpg-to-pdf', 'check-pdf-before-sending', 'privacy', 'guides'],
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: ['id photo maker', 'passport photo crop'],
  },
  {
    path: 'check-pdf-before-sending',
    kind: 'tool',
    h1: 'Check a PDF before sending',
    keyword: 'check pdf before sending',
    description: 'Scan a PDF for hidden text, scripts, and old revisions with no upload. A clean result is not a promise.',
    toolId: 'share-check',
    essay:
      'Check a PDF before sending looks for signals: more than one file ending, a script marker, an attachment, a GPS tag, text under a dark shape, white text, and text parked off the page. Each hit is one sentence grouped as high, medium, or info. Fix all rebuilds the pages without those markers and then runs the check again. Nothing risky found is shown only when the second check is empty. That sentence means this checker is quiet. It does not mean a person could not still find something another tool would see. A black rectangle left over a sentence is reported, because the words can remain underneath.',
    steps: how('Check a PDF before sending'),
    points: why('the scan reads bytes in this tab and the fix writes a new file beside that reading.'),
    facts: localFacts(
      'Check a PDF before sending',
      'You get a short list. Fix rebuilds the file and scans it again. Covered text that this parser understands is dropped.',
      'Do not skip reading the list because the button said fix. If a line remains, the file is not clear of that signal.',
      'Open the download and search for a word you expected to be gone. If search finds it, do not send the file.',
    ),
    related: ['remove-metadata-from-pdf', 'redact-pdf', 'privacy', 'compress-pdf', 'is-this-pdf-signed', 'guides'],
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: ['check pdf before sending', 'hidden text in pdf'],
  },
  {
    path: 'remove-metadata-from-pdf',
    kind: 'tool',
    h1: 'Remove metadata from a PDF',
    keyword: 'remove pdf metadata',
    description: 'Strip author and software names from a PDF with no upload. The check tells you what it still sees.',
    toolId: 'share-check',
    essay:
      'Remove metadata from a PDF uses the same on-device check as the before-you-send tool, with attention on author, creator, and producer strings, plus GPS tags inside embedded photos. The rebuild writes a new file and drops the info dictionary it can reach. A fresh save can still carry a modification time. The list after the fix is the record of what remains. This is not a forensic wipe. Incremental endings are collapsed because the new file is saved once. If your goal is permanent redaction of a sentence, use a tool that deletes the text itself. A metadata wipe does not black out a paragraph.',
    steps: how('Remove metadata from a PDF'),
    points: why('names stored in the file info are cleared in the copy this tab writes.'),
    facts: localFacts(
      'Remove metadata from a PDF',
      'Author and software strings this reader can see are removed in the new file. The scan runs again so you can see leftovers.',
      'Do not use a metadata wipe as redaction. The words of the document are a different problem.',
      'Open the file in a viewer that shows document properties. The old author line should be gone.',
    ),
    related: ['check-pdf-before-sending', 'privacy', 'compress-pdf', 'redact-pdf', 'is-this-pdf-signed', 'guides'],
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: ['remove pdf metadata', 'strip pdf author'],
  },
  {
    path: 'pdf-commands',
    kind: 'tool',
    h1: 'Plain language PDF commands',
    keyword: 'pdf voice command',
    description: 'Turn a short sentence into PDF steps with no upload. The plan waits for Run.',
    toolId: 'commands',
    essay:
      'Plain language PDF commands reads sentences such as making a file smaller and dropping a page. A built-in parser covers sizes, ranges, rotate, merge, split, grayscale, page numbers, watermarks, and a password request. The password step is shown and then refused, because this version cannot encrypt. If the sentence is not recognised and the browser has an on-device prompt API, the page says so and still does not call a cloud model. You always see numbered steps and press Run. Edit returns you to the sentence. Closing the tab drops the file. The plan is steps only.',
    steps: how('Plain language PDF commands'),
    points: why('the sentence is parsed here, and the file is not sent out to be understood.'),
    facts: localFacts(
      'Plain language PDF commands',
      'You see a numbered plan. Run is the confirmation. An unknown sentence does not silently do something else.',
      'Do not expect a password step to lock the file. The line says it will not run.',
      'Read the plan. If it says delete page 3, that is the page that will be dropped after you press Run.',
    ),
    related: ['compress-pdf', 'split-pdf', 'merge-pdf', 'pdf-workflows', 'add-page-numbers-to-pdf', 'guides'],
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: ['pdf command', 'compress and delete page'],
  },
  {
    path: 'make-pdf-accessible',
    kind: 'tool',
    h1: 'Make a PDF accessible',
    keyword: 'make pdf accessible',
    description: 'Read an on-device accessibility report with no upload. Tags still need a person.',
    toolId: 'accessible',
    essay:
      'Make a PDF accessible reports title, language, a structure tree if one exists, the marked flag, figures, contrast, and bookmarks on long files. Pass means the marker is present. Fix available means you can type a title and a language. Needs a human means this version will not invent headings, lists, table headers, or alt text. No layout model is bundled, so reading order is not rewritten. The report is free. The page says automatic fixes are limited and points you to a screen reader and to external checkers. It does not claim PDF/UA compliance.',
    steps: how('Make a PDF accessible'),
    points: why('the report reads the file structure in this tab and does not send it to a validator.'),
    facts: localFacts(
      'Make a PDF accessible',
      'You get pass, fix, or needs a human for each item. Tags are not fabricated. Title text is whatever you type.',
      'Do not file this report as a legal conformance claim. Test with a screen reader.',
      'Look for Needs a human on figures and contrast. Those lines are intentional, not a crash.',
    ),
    related: ['pdf-to-word', 'ocr-pdf', 'privacy', 'edit-pdf', 'guides', 'compress-pdf'],
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: ['make pdf accessible', 'pdf ua check'],
  },
  {
    path: 'is-this-pdf-signed',
    kind: 'tool',
    h1: 'Is this PDF signed',
    keyword: 'check pdf signature',
    description: 'See whether a PDF has a signature byte range, with no upload. Wording stops short of a verdict.',
    toolId: 'genuine',
    essay:
      'Is this PDF signed looks for a signature byte range, counts file endings, and compares creator and producer strings. A range that does not cover the file is described as changed after signing. No range is described as no signature. Certificate chain status is not judged, because no trust list is bundled, and revocation is described as not checked offline. A Content Credentials marker is reported when the bytes contain one, without verifying the manifest. The page never says fake or authentic. No signs of editing found is paired with a reminder that this does not prove the document is genuine. An earlier revision is not reconstructed. Compare needs the earlier file from you.',
    steps: how('Is this PDF signed'),
    points: why('byte ranges and info strings are read locally, with no call to a trust service.'),
    facts: localFacts(
      'Is this PDF signed',
      'You get careful lines: no signature, changed after signing, or signs of editing. None of them is a court opinion.',
      'Do not tell someone a contract is genuine because this page was quiet. Quiet is not proof.',
      'If the line says changed after signing, get the signed original from the signer before you rely on this copy.',
    ),
    related: ['check-pdf-before-sending', 'compare-pdf', 'privacy', 'protect-pdf', 'unlock-pdf', 'guides'],
    guides,
    intent: 'informational',
    priority: 2,
    keywords: ['check pdf signature', 'was this pdf changed'],
  },
  {
    path: 'chat-with-pdf',
    kind: 'tool',
    h1: 'Chat with a PDF',
    keyword: 'chat with pdf privately',
    description: 'Ask questions that are answered from the PDF text, with no upload. Each answer cites a page.',
    toolId: 'chat',
    essay:
      'Chat with a PDF extracts the text of each page into memory and answers from those words. If a question is not in the document, the reply is that it could not be found. There is no general-knowledge fallback. Page buttons jump to the extracted passage. A browser on-device prompt is used only when it exists and only with the passages already retrieved. A downloadable private model is not published with this version, so the button is not offered. The index is cleared when you close the document. Summaries, dates, and clause hints are searches over the same text, still cited. Scans without a text layer produce little to search, and this version does not OCR them in secret.',
    steps: how('Chat with a PDF'),
    points: why('the answer is limited to text read from the file in this tab.'),
    facts: localFacts(
      'Chat with a PDF',
      'You get a quotation with a page number, or a sentence that the document does not contain the answer.',
      'Do not ask for a fact that is not in the file and expect a guess. The refusal is the feature.',
      'Click the page button and read the passage. If it does not support the sentence, ignore the sentence.',
    ),
    related: ['summarize-pdf', 'pdf-to-markdown', 'ocr-pdf', 'privacy', 'compare-pdf', 'guides'],
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: ['chat with pdf privately', 'ask a pdf a question'],
  },
  {
    path: 'hot-folders',
    kind: 'tool',
    h1: 'Hot folders',
    keyword: 'pdf hot folder',
    description: 'Watch a folder for PDFs while the app is open, with no upload. Originals are left in place.',
    toolId: 'hot-folders',
    essay:
      `Hot folders is for desktop Chromium. Other browsers get one line explaining the feature is hidden because the file-system picker is missing. You pick an input folder and the app writes copies into a ${brandName()} output folder. It does not overwrite or delete the original. Watching uses a five-second check while the tab is open, and the page says the work runs only while ${brandName()} is open. A permission error pauses that file and the queue continues. The activity log stays in the page. Closing the tab stops the watch. Nothing is uploaded to keep the watch alive.`,
    steps: how('Hot folders'),
    points: why('the folder permission stays in this browser and the bytes are copied on this machine.'),
    facts: localFacts(
      'Hot folders',
      `New PDFs are copied into ${brandName()} output with a -copy name. They are not compressed. The source file remains. The log lists each result.`,
      'Do not close the tab and expect the watch to continue. It runs only while the app is open.',
      'Check the output folder. The original name should still be in the input folder.',
    ),
    related: ['pdf-workflows', 'compress-pdf', 'privacy', 'lite', 'guides', 'offline-pdf-tools'],
    guides,
    intent: 'commercial',
    priority: 2,
    keywords: ['pdf hot folder', 'watch folder compress pdf'],
  },
  {
    path: 'lite',
    kind: 'tool',
    h1: 'Lite PDF tools',
    keyword: 'lite pdf tools',
    description: 'Use a lighter PDF path on a slow connection with no upload. Models stay unloaded.',
    toolId: 'lite',
    essay:
      'Lite PDF tools turns animations off and points you at Compress, Merge, Images to PDF, ID photo resize, and Safe to share. It turns itself on when the browser reports save-data, a 2G or 3G connection, or about two gigabytes of memory, and you can open this page directly. The initial script for the whole app is already small. Lite does not fetch a model. Thumbnails stay on the ordinary path. A better connection later does not change the privacy rule: files are still processed here. Use Settings to leave lite mode. The page is the same origin as the rest of the site.',
    steps: how('Lite PDF tools'),
    points: why('lite mode only changes what this page loads and animates, not where the file goes.'),
    facts: localFacts(
      'Lite PDF tools',
      'Animations stop and the suggested tools are the small set. No model download starts.',
      'Do not expect Office conversion or a chat model in lite mode. Those stay on the full pages.',
      'Open Compress from this page and confirm the status still says the work is on this device.',
    ),
    related: ['compress-pdf', 'merge-pdf', 'jpg-to-pdf', 'id-photo', 'check-pdf-before-sending', 'guides'],
    guides,
    intent: 'informational',
    priority: 2,
    keywords: ['lite pdf tools', 'pdf tools slow connection'],
  },
  {
    path: 'help/url-parameters',
    kind: 'legal',
    h1: 'URL parameters for PDF tools',
    keyword: 'pdf tool url parameters',
    description: 'Open a PDF tool with a target size or a page range in the URL. No upload is added by these parameters.',
    essay:
      'URL parameters for PDF tools document the query strings the pages already understand. /compress-pdf?target=200kb opens Compress and treats 200 KB as a goal, not a guarantee. /compress-image?target=50kb does the same for images. /compress-pdf?gray=1 starts the black and white option. /split-pdf?pages=1-3 fills the range box. /presets/ followed by an id opens Get it accepted for that record, and a draft id is refused. Controls on these pages have accessible names, and the main buttons carry data-action attributes for tests and for a future agent hook. If the browser exposes a standard way to offer tools to an assistant, the app registers compress, merge, split, presets, and the share check. The registration only opens a local page.',
    steps: how('URL parameters'),
    points: why('a query string only sets options in this tab.'),
    facts: localFacts(
      'URL parameters',
      'The address sets a goal or a page range. It does not upload the file and it does not call an assistant by itself.',
      'Do not put a secret in the address bar. The query is options, and it can stick in local history on this device.',
      'Open /compress-pdf?target=200kb and read the goal line before you add a file.',
    ),
    related: ['compress-pdf', 'split-pdf', 'get-it-accepted', 'check-pdf-before-sending', 'privacy', 'guides'],
    guides,
    intent: 'informational',
    priority: 1,
    keywords: ['pdf tool url parameters', 'compress pdf target query'],
  },
  {
    path: 'signature-resizer',
    kind: 'tool',
    h1: 'Signature resizer for online forms',
    keyword: 'signature resizer',
    title: 'Signature Resizer – Clean Background & Exact KB | Weesize',
    description: 'Clean background to white, darken ink, and resize signature to exact KB and pixels with no upload.',
    toolId: 'signature-resizer',
    essay:
      'Signature resizer prepares photo scans and mobile camera pictures of pen signatures for online forms, exams, and government portals. The processing runs directly in your browser. It crops excess borders, enhances contrast, cleans paper background to pure white, deepens ink darkness, and scales to exact dimensions and KB limits required by JEE, NEET, SSC, UPSC, and visa portals. Your signature stays on this device.',
    steps: how('Signature resizer'),
    points: why('signature editing and whitening runs 100% locally in your browser memory.'),
    facts: localFacts(
      'Signature resizer for online forms',
      'Crops signature ink bounds, whitens background paper, and darkens pen contrast.',
      'Supports exact pixel dimensions (such as 140×60 px) and exact file size limits in KB.',
      'All processing runs inside client-side canvas without remote server calls.',
    ),
    related: ['id-photo', 'compress-image', 'compress-pdf', 'tools', 'privacy'],
    guides,
    intent: 'commercial',
    priority: 1,
    keywords: ['signature resizer', 'resize signature for online application', 'darken signature'],
  },
];
