import { how, localFacts, why, type Seed } from './factory';

export const toolSeedsB: Seed[] = [
  {
    path: 'sign-pdf',
    kind: 'tool',
    h1: 'Sign PDF',
    keyword: 'sign pdf',
    title: 'Sign PDF – Free, No Upload | Weesize',
    description: 'Draw, type or upload your signature and sign PDFs in seconds. Free, no account, and your document never leaves your device.',
    toolId: 'sign',
    essay:
      'Sign PDF is listed because people search for it. This version does not place a cryptographic signature, and it will not draw an image and call the file signed. A typed name and a certificate are different things. Uploading a contract so a website can “sign” it also hands that contract to the operator. Until this app can create a signature it can explain, the page stops. The guide separates a handwritten scan, a certificate, and a picture of handwriting.',
    steps: how('Sign PDF'),
    points: why('the honest limit is shown here, and the contract is not uploaded just to be signed.'),
    facts: localFacts(
      'Sign PDF',
      'No certificate is created and no signature image is stamped. Either one, done quietly, would be a false result.',
      'A JPEG of handwriting is not a qualified electronic signature. Use a process that names the certificate if you need one.',
      'There is no signed download from this action. Do not treat an unchanged file as signed.',
    ),
    related: ['pdf-forms', 'edit-pdf', 'watermark-pdf', 'merge-pdf', 'compress-pdf', 'protect-pdf'],
    guides: ['guides/sign-a-pdf-without-printing', 'guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'commercial',
    priority: 2,
    keywords: ['sign pdf', 'sign pdf online'],
  },
  {
    path: 'edit-pdf',
    kind: 'tool',
    h1: 'Edit PDF',
    keyword: 'edit pdf',
    description: 'See what editing a PDF means here, with no upload. This version is not a full desktop editor.',
    toolId: 'edit',
    essay:
      'Edit PDF, on many sites, means upload the file and move text around. This version does not offer that canvas, and it says so in one sentence. Rotate, crop, watermark, page numbers, merge, split, and organize do run locally. Rewriting a paragraph inside a designed PDF is a different job. Use the program that created the file, on a machine you control, so the document still does not have to be uploaded to a random site.',
    steps: how('Edit PDF'),
    points: why('the limit is stated before any file is touched, so nothing is uploaded for a fake edit.'),
    facts: localFacts(
      'Edit PDF',
      'The working edits are rotate, crop, watermark, numbers, merge, split, and organize. A general text editor is not opened.',
      'Do not expect to restyle a brochure here. This page will not imitate a desktop publishing program.',
      'If you needed a real edit, confirm you used the specific tool and open that download. This screen does not disguise a file.',
    ),
    related: ['watermark-pdf', 'add-page-numbers-to-pdf', 'organize-pdf', 'crop-pdf', 'sign-pdf', 'merge-pdf'],
    guides: ['guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/sign-a-pdf-without-printing', 'guides/how-to-redact-a-pdf-properly'],
    intent: 'commercial',
    priority: 2,
    keywords: ['edit pdf', 'pdf editor'],
  },
  {
    path: 'redact-pdf',
    kind: 'tool',
    h1: 'Redact PDF',
    keyword: 'redact pdf',
    description: 'Learn how PDF redaction works, with no upload. A white box is not redaction, and this version will not pretend.',
    toolId: 'redact',
    essay:
      'Redact PDF should remove the underlying text, not paint over it. A white rectangle leaves the words in the file, where someone can copy them. This version will not draw that rectangle and call it redaction. Until a pass can delete the text and then show that it is gone, there is no button that claims to redact. Do not upload a sensitive file to a website to learn this the hard way.',
    steps: how('Redact PDF'),
    points: why('the file stays here, and you are not offered a false black-box download.'),
    facts: localFacts(
      'Redact PDF',
      'Nothing is marked redacted in this version, because that mark would be a lie without removing the text.',
      'Highlighting, a white shape, or a crop is the wrong tool for names, account numbers, or health details.',
      'If you can still select the words or search for them, they were not removed. Do not send that file.',
    ),
    related: ['crop-pdf', 'edit-pdf', 'protect-pdf', 'compress-pdf', 'compare-pdf', 'watermark-pdf'],
    guides: ['guides/how-to-redact-a-pdf-properly', 'guides/why-black-boxes-fail-at-redaction', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'commercial',
    priority: 1,
    keywords: ['redact pdf', 'pdf redaction'],
  },
  {
    path: 'ocr-pdf',
    kind: 'tool',
    h1: 'OCR PDF',
    keyword: 'ocr pdf',
    description: 'See the honest limit for OCR PDF, with no upload. This version does not invent a text layer for a scan.',
    toolId: 'ocr',
    essay:
      'OCR PDF means reading the pixels of a scan and adding a real text layer. This version does not include that engine, so it will not guess the words and hide the guesses under the picture. The guide explains what a text layer is. When you do use OCR, prefer a tool that runs on your machine. Uploading a passport scan to make it searchable is how that scan leaves your hands.',
    steps: how('OCR PDF'),
    points: why('no scan is uploaded to a recognition service from this page.'),
    facts: localFacts(
      'OCR PDF',
      'No text layer is added. Search will not find words that were only pixels.',
      'Do not trust a claim of perfect OCR with no way to check the text. This page will not make that claim.',
      'Try to select a word on the scan. If you cannot, there is still no text layer, which is the expected result here.',
    ),
    related: ['pdf-to-word', 'scan-to-pdf', 'compress-pdf', 'pdf-to-jpg', 'repair-pdf', 'edit-pdf'],
    guides: ['guides/make-a-scanned-pdf-searchable', 'guides/pdf-to-word-what-you-keep', 'guides/why-is-my-pdf-so-large'],
    intent: 'commercial',
    priority: 1,
    keywords: ['ocr pdf', 'searchable pdf'],
  },
  {
    path: 'protect-pdf',
    kind: 'tool',
    h1: 'Protect PDF',
    keyword: 'protect pdf',
    description: 'Read how PDF passwords work, with no upload. This version will not pretend a file is encrypted.',
    toolId: 'protect',
    essay:
      'Protect PDF usually means encrypting the file with a password you choose. This version does not include that encryption, and it will not set a flag that a reader can ignore. A fake lock is worse than no lock: you might email a file you believe is closed. Use a desktop tool you can name, on this computer, if you need a real password. Do not upload the confidential file to test a website’s lock icon.',
    steps: how('Protect PDF'),
    points: why('the file is not uploaded in exchange for a lock icon this app cannot stand behind.'),
    facts: localFacts(
      'Protect PDF',
      'No password is applied. An unprotected file stays unprotected, and the page tells you that.',
      'A mail-account password is not PDF encryption. Do not confuse the two.',
      'This page will not give you a locked file to test, because it did not lock one.',
    ),
    related: ['unlock-pdf', 'redact-pdf', 'compress-pdf', 'watermark-pdf', 'sign-pdf', 'edit-pdf'],
    guides: ['guides/password-protect-a-pdf', 'guides/remove-a-pdf-password-you-know', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'commercial',
    priority: 2,
    keywords: ['protect pdf', 'password protect pdf'],
  },
  {
    path: 'unlock-pdf',
    kind: 'tool',
    h1: 'Unlock PDF',
    keyword: 'unlock pdf',
    description: 'See how to unlock a PDF you can already open, with no upload. This app will not guess a password.',
    toolId: 'unlock',
    essay:
      'Unlock PDF is for a password you already know. This version does not strip encryption, and it will never try passwords. Guessing is an attack, even when the file is yours and you have forgotten the word. Remove the password on this device with a tool that can, then continue. Uploading a locked file to a remover gives that service the file and often the password you type.',
    steps: how('Unlock PDF'),
    points: why('there is no password field sent to a server, because there is no guessing and no upload.'),
    facts: localFacts(
      'Unlock PDF',
      'This version does not remove encryption. A locked file stays locked here.',
      'If you do not know the password, no reputable tool should offer to find it.',
      'There is no unlocked download from this screen. A file unlocked elsewhere should open without a prompt.',
    ),
    related: ['protect-pdf', 'repair-pdf', 'compress-pdf', 'edit-pdf', 'merge-pdf', 'redact-pdf'],
    guides: ['guides/remove-a-pdf-password-you-know', 'guides/password-protect-a-pdf', 'guides/what-a-browser-pdf-tool-can-and-cannot-do'],
    intent: 'commercial',
    priority: 2,
    keywords: ['unlock pdf', 'remove pdf password'],
  },
  {
    path: 'compress-image',
    kind: 'tool',
    h1: 'Compress image',
    keyword: 'compress image',
    title: 'Compress Image – Pick an Exact Size, Free | Weesize',
    description: 'Compress JPG, PNG, and WebP images to exact KB targets. Free, unlimited, and 100% private with no upload: files stay on your device. Shrink now.',
    toolId: 'compress-images',
    essay:
      'Compress image resizes and re-encodes a picture in this browser. JPEG and WebP can step down in quality. PNG is lossless, so it gets smaller by shrinking pixel dimensions when a size goal asks for that. Location data is not copied into the new file. The tool stops at a floor and the status line tells you the size it reached. HEIC and AVIF open only when this browser already understands them.',
    steps: how('Compress image'),
    points: why('pixels are processed on this device, not on an image CDN.'),
    facts: localFacts(
      'Compress image',
      'JPEG and WebP quality can drop. PNG gets smaller by resizing. The new file does not keep camera location data.',
      'Do not compress a picture you still need at full size for print. Keep the original and send the smaller copy.',
      'Read the status line for the size you got, then look at the subject. A melted caption means the target was too low.',
    ),
    related: ['jpg-to-pdf', 'compress-pdf', 'png-to-jpg', 'jpg-to-webp', 'webp-to-jpg', 'reduce-photo-size'],
    neighbors: [],
    guides: ['guides/best-image-format-for-the-web', 'guides/shrink-photos-for-applications', 'guides/compress-images-for-email'],
    intent: 'transactional',
    priority: 1,
    keywords: ['compress image', 'reduce image size', 'photo compressor'],
  },
  {
    path: 'pdf-to-excel',
    kind: 'tool',
    h1: 'PDF to Excel',
    keyword: 'pdf to excel',
    description: 'See the limit for PDF to Excel, with no upload. This version will not invent a spreadsheet.',
    toolId: 'pdf-excel',
    essay:
      'PDF to Excel is a common place to upload bank statements. This version does not rebuild tables into cells. Guessing which gap is a column moves numbers into the wrong cell. The page refuses that guess. If the PDF has a text layer, PDF to Word or PDF to Markdown can give you the words locally, and you can place the numbers yourself.',
    steps: how('PDF to Excel'),
    points: why('a statement is not uploaded in exchange for a spreadsheet this app cannot check.'),
    facts: localFacts(
      'PDF to Excel',
      'No cells are inferred. A wrong column is worse than no file, so this version emits no workbook.',
      'Take a text export and build the sheet yourself when the numbers matter.',
      'There is no xlsx to sum from this screen. A grid you trust should be visible before you rely on it.',
    ),
    related: ['excel-to-pdf', 'pdf-to-word', 'pdf-to-markdown', 'ocr-pdf', 'compress-pdf', 'compare-pdf'],
    guides: ['guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/pdf-to-word-what-you-keep', 'guides/make-a-scanned-pdf-searchable'],
    intent: 'commercial',
    priority: 2,
    keywords: ['pdf to excel', 'pdf to xlsx'],
  },
  {
    path: 'excel-to-pdf',
    kind: 'tool',
    h1: 'Excel to PDF',
    keyword: 'excel to pdf',
    description: 'See the limit for Excel to PDF, with no upload. This version will not invent a print layout.',
    toolId: 'excel',
    essay:
      'Excel to PDF needs column widths, repeating headers, and page breaks. This version will not invent that layout and call it your sheet. Export from the spreadsheet program, on this computer, when the grid must be faithful. This page exists so the search does not dead-end on a fake converter, and so a workbook of customer data is not nudged into an upload form.',
    steps: how('Excel to PDF'),
    points: why('the workbook stays put, because this page will not upload it for a layout it cannot verify.'),
    facts: localFacts(
      'Excel to PDF',
      'No print area is guessed. A guessed page break can hide a column, so no PDF of the grid is produced here.',
      'Use the spreadsheet’s own export when fidelity matters. Word to PDF here is for paragraphs, not for a sheet.',
      'You should not receive a PDF from this screen. A PDF from the original app should be checked column by column.',
    ),
    related: ['pdf-to-excel', 'word-to-pdf', 'html-to-pdf', 'compress-pdf', 'merge-pdf', 'jpg-to-pdf'],
    guides: ['guides/word-to-pdf-what-changes', 'guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'commercial',
    priority: 3,
    keywords: ['excel to pdf', 'xlsx to pdf'],
  },
  {
    path: 'pdf-to-powerpoint',
    kind: 'tool',
    h1: 'PDF to PowerPoint',
    keyword: 'pdf to powerpoint',
    description: 'See the limit for PDF to PowerPoint, with no upload. Slides are not reconstructed here.',
    toolId: 'pdf-ppt',
    essay:
      'PDF to PowerPoint asks a converter to decide what was a title and what was a picture. This version does not make those guesses, and it does not upload the deck so a service can. If you still have the presentation, start there. If you only have the PDF, PDF to JPG gives you a picture of each page, locally, which is an honest fallback when you need to show the pages rather than edit them as slides.',
    steps: how('PDF to PowerPoint'),
    points: why('the deck is not uploaded to be turned into slides this app cannot check.'),
    facts: localFacts(
      'PDF to PowerPoint',
      'Titles and bullets are not inferred. No pptx is built. A picture of the page is a different export.',
      'Choose PDF to JPG to show pages. Choose the original presentation to edit slides.',
      'There is no slide file from this screen to open in a presentation program.',
    ),
    related: ['powerpoint-to-pdf', 'pdf-to-jpg', 'pdf-to-word', 'compress-pdf', 'merge-pdf', 'edit-pdf'],
    guides: ['guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/pdf-to-word-what-you-keep', 'guides/best-image-format-for-the-web'],
    intent: 'commercial',
    priority: 3,
    keywords: ['pdf to powerpoint', 'pdf to pptx'],
  },
  {
    path: 'powerpoint-to-pdf',
    kind: 'tool',
    h1: 'PowerPoint to PDF',
    keyword: 'powerpoint to pdf',
    description: 'See the limit for PowerPoint to PDF, with no upload. This version will not invent a slide layout.',
    toolId: 'ppt',
    essay:
      'PowerPoint to PDF should preserve slide size and fonts. This version does not import pptx into a layout it can stand behind, so it will not emit a PDF and hope. Export from the presentation program on this device when the slides must match. If you already have a PDF of the slides and it is huge because every slide is a picture, Compress PDF is the tool that can help.',
    steps: how('PowerPoint to PDF'),
    points: why('the presentation is not uploaded for a conversion this version cannot verify.'),
    facts: localFacts(
      'PowerPoint to PDF',
      'No slide is rasterized by this tool. Use the presentation app’s export for a faithful PDF.',
      'A huge exported PDF is a compression problem. Open Compress PDF for that, not a second converter.',
      'Do not expect a download from this screen. Check a PDF from the original app full-screen against the slides.',
    ),
    related: ['pdf-to-powerpoint', 'compress-pdf', 'jpg-to-pdf', 'word-to-pdf', 'merge-pdf', 'pdf-to-jpg'],
    guides: ['guides/why-is-my-pdf-so-large', 'guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/reduce-pdf-size-without-losing-quality'],
    intent: 'commercial',
    priority: 3,
    keywords: ['powerpoint to pdf', 'pptx to pdf'],
  },
  {
    path: 'html-to-pdf',
    kind: 'tool',
    h1: 'HTML to PDF',
    keyword: 'html to pdf',
    description: 'Turn HTML you paste into a PDF, with no upload and no fetching of web addresses.',
    toolId: 'html',
    essay:
      'HTML to PDF accepts markup you paste or a file you choose. It does not fetch a URL. Fetching would send a request and could pull a page you did not mean to hand to a converter. Scripts are not run, and remote images are not loaded. If the page depends on a stylesheet on the network, it will look plainer here than in a browser, on purpose.',
    steps: how('HTML to PDF'),
    points: why('no web address is fetched, so the only HTML involved is what you pasted or opened.'),
    facts: localFacts(
      'HTML to PDF',
      'Local text is written into a PDF. Remote images and scripts are not downloaded or executed.',
      'Do not paste a page that only makes sense after JavaScript runs. You will get the raw text, not the app screen.',
      'If a figure is missing from the PDF, it lived on another server and was correctly left out.',
    ),
    related: ['word-to-pdf', 'pdf-to-markdown', 'jpg-to-pdf', 'compress-pdf', 'merge-pdf', 'edit-pdf'],
    guides: ['guides/html-to-pdf-without-fetching-the-web', 'guides/word-to-pdf-what-changes', 'guides/what-a-browser-pdf-tool-can-and-cannot-do'],
    intent: 'transactional',
    priority: 2,
    keywords: ['html to pdf', 'webpage to pdf'],
  },
  {
    path: 'pdf-to-markdown',
    kind: 'tool',
    h1: 'PDF to Markdown',
    keyword: 'pdf to markdown',
    description: 'Extract PDF text as Markdown in the browser with no upload. You get the words, not a rebuilt design.',
    toolId: 'pdf-md',
    essay:
      'PDF to Markdown extracts the text layer and writes a Markdown file on this device. Headings are not detected with perfect confidence; you get a readable text dump you can edit. Scans without a text layer produce little, and the tool does not OCR them quietly. Use this when you want notes in a text editor without handing the PDF to a chat site.',
    steps: how('PDF to Markdown'),
    points: why('the text file is written here, not pasted into an online converter.'),
    facts: localFacts(
      'PDF to Markdown',
      'You get Markdown of the text layer. Layout and images are not reproduced as figures.',
      'A scan without OCR will not become a full transcript here.',
      'Search the Markdown for a sentence you can see in the PDF. If it is there, the text layer was real.',
    ),
    related: ['pdf-to-word', 'ocr-pdf', 'html-to-pdf', 'compare-pdf', 'compress-pdf', 'edit-pdf'],
    guides: ['guides/pdf-to-word-what-you-keep', 'guides/make-a-scanned-pdf-searchable', 'guides/html-to-pdf-without-fetching-the-web'],
    intent: 'transactional',
    priority: 2,
    keywords: ['pdf to markdown', 'pdf to md'],
  },
  {
    path: 'pdf-to-pdfa',
    kind: 'tool',
    h1: 'PDF to PDF/A',
    keyword: 'pdf to pdfa',
    description: 'Read what PDF/A requires, with no upload. This version will not label a file as archival unless it can check.',
    toolId: 'pdfa',
    essay:
      'PDF to PDF/A is an archival conversion with rules about fonts, color, and metadata. This version will not stamp a PDF/A claim on a file it did not validate. A false archival label is worse than no label, because a records office might accept it. If a portal demands PDF/A, use a checker you trust on a machine you control, not a badge from a site that received the record.',
    steps: how('PDF to PDF/A'),
    points: why('the file is not uploaded to receive an archival badge this app cannot verify.'),
    facts: localFacts(
      'PDF to PDF/A',
      'No conformance claim is written. Fonts are not embedded by a fake pass.',
      'Do not rename a normal PDF to imply it is PDF/A. The label is a claim about the file’s insides.',
      'A real PDF/A file should pass a validator. This page will not hand you a renamed ordinary PDF.',
    ),
    related: ['compress-pdf', 'repair-pdf', 'pdf-to-word', 'protect-pdf', 'edit-pdf', 'ocr-pdf'],
    guides: ['guides/pdf-vs-pdfa', 'guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'informational',
    priority: 2,
    keywords: ['pdf to pdfa', 'pdf/a converter'],
  },
  {
    path: 'compare-pdf',
    kind: 'tool',
    h1: 'Compare PDF',
    keyword: 'compare pdf',
    description: 'Compare the words in two PDFs in the browser with no upload. Pictures are not part of this check.',
    toolId: 'compare',
    essay:
      'Compare PDF reads the text layer of two files and shows a word-level difference. It does not overlay pages visually, and it does not notice a moved logo if the words stayed the same. Both files stay on this device, which matters for contract drafts. Scans without text compare as empty. Read the pages yourself before you sign.',
    steps: how('Compare PDF'),
    points: why('both drafts stay in memory here, so a contract is not uploaded to a diff service.'),
    facts: localFacts(
      'Compare PDF',
      'You get a word difference of the text layers. Visual changes without text changes can be missed.',
      'Do not compare scans here and conclude the pictures match. Empty text is not proof.',
      'Read the inserted and deleted words, then open both PDFs on the page that changed.',
    ),
    related: ['pdf-to-word', 'merge-pdf', 'compress-pdf', 'redact-pdf', 'edit-pdf', 'organize-pdf'],
    guides: ['guides/compare-two-contract-versions', 'guides/pdf-to-word-what-you-keep', 'guides/how-to-redact-a-pdf-properly'],
    intent: 'transactional',
    priority: 2,
    keywords: ['compare pdf', 'pdf diff'],
  },
  {
    path: 'add-page-numbers-to-pdf',
    kind: 'tool',
    h1: 'Add page numbers to PDF',
    keyword: 'add page numbers to pdf',
    description: 'Add page numbers to a PDF in the browser with no upload. Choose a start number and skip a cover if you need to.',
    toolId: 'numbers',
    essay:
      'Add page numbers to PDF draws a number on each page, on this device. You can start at a number other than 1 and skip the first page when that page is a cover. The numbers are painted into the file. They will not fix a table of contents that already has the wrong pages. Check the corners so the number does not sit on a footer you already had.',
    steps: how('Add page numbers'),
    points: why('numbers are drawn into a copy in this browser, not by an online stamp service.'),
    facts: localFacts(
      'Add page numbers to PDF',
      'Each page gets a number, unless you skip the first. The start value is the one you set.',
      'Page numbers do not pretend a missing page was never there. The count follows the pages in the file.',
      'Open the last page and confirm the number matches the count you expect, including a skipped cover.',
    ),
    related: ['watermark-pdf', 'organize-pdf', 'merge-pdf', 'compress-pdf', 'split-pdf', 'edit-pdf'],
    guides: ['guides/add-page-numbers', 'guides/organize-pages-before-you-send', 'guides/watermark-a-contract'],
    intent: 'transactional',
    priority: 2,
    keywords: ['add page numbers to pdf', 'number pdf pages'],
  },
  {
    path: 'watermark-pdf',
    kind: 'tool',
    h1: 'Watermark PDF',
    keyword: 'watermark pdf',
    description: 'Add a text watermark to a PDF in the browser with no upload. The words are drawn on the pages locally.',
    toolId: 'watermark',
    essay:
      'Watermark PDF draws a short text mark, such as Draft, across the pages. The mark is visible content, not a sticky note every reader can toggle off. It is not a security control and it is not redaction: the words underneath remain readable. Use it so a draft is obviously a draft. Do not use it to hide a figure.',
    steps: how('Watermark PDF'),
    points: why('the draft mark is drawn locally, so the unreleased file is not uploaded to be stamped.'),
    facts: localFacts(
      'Watermark PDF',
      'The mark is part of the page content. It is a label, not encryption and not redaction.',
      'Do not watermark a page in order to hide a number. The number is still there.',
      'Open a page and read the mark. It should say what you typed, and the text under it should still be readable.',
    ),
    related: ['add-page-numbers-to-pdf', 'compress-pdf', 'merge-pdf', 'edit-pdf', 'protect-pdf', 'organize-pdf'],
    guides: ['guides/watermark-a-contract', 'guides/add-page-numbers', 'guides/how-to-redact-a-pdf-properly'],
    intent: 'transactional',
    priority: 2,
    keywords: ['watermark pdf', 'draft watermark'],
  },
  {
    path: 'repair-pdf',
    kind: 'tool',
    h1: 'Repair PDF',
    keyword: 'repair pdf',
    description: 'Rebuild a PDF’s structure in the browser with no upload. This is a limited repair, not a recovery promise.',
    toolId: 'repair',
    essay:
      'Repair PDF reloads the file and saves it again, which rebuilds the cross-reference a reader uses to find objects. That fixes some files that open in one viewer and fail in another. It does not recover bytes that were never downloaded, and it does not decrypt a password. If the file cannot be read as a PDF at all, export it again from the program that created it. The attempt stays on this device.',
    steps: how('Repair PDF'),
    points: why('the rebuild happens in memory here, including the cases where the file cannot be saved.'),
    facts: localFacts(
      'Repair PDF',
      'A successful repair rewrites the structure the viewer needs. Missing bytes are not invented.',
      'A password-locked file is not repaired by guessing. A truncated download may be beyond this pass.',
      'Open the download in the viewer that failed before. If it still fails, export again from the source program.',
    ),
    related: ['compress-pdf', 'unlock-pdf', 'merge-pdf', 'ocr-pdf', 'pdf-to-pdfa', 'organize-pdf'],
    guides: ['guides/repair-a-damaged-pdf', 'guides/remove-a-pdf-password-you-know', 'guides/why-is-my-pdf-so-large'],
    intent: 'transactional',
    priority: 2,
    keywords: ['repair pdf', 'fix damaged pdf'],
  },
  {
    path: 'scan-to-pdf',
    kind: 'tool',
    h1: 'Scan to PDF',
    keyword: 'scan to pdf',
    description: 'Scan pages to a PDF with the camera, in the browser, with no upload. This beta does not fake edge detection.',
    toolId: 'scan',
    essay:
      'Scan to PDF uses the camera on this device, captures stills, and builds a PDF here. It does not detect page corners with a model, and it does not upload the frames to a scanning cloud. You get a picture of the page, not a text layer. If you need search, that is OCR, which this version does not fake. Frames are not a product for a server.',
    steps: how('Scan to PDF'),
    points: why('camera frames become a PDF in memory and are not posted to a scan account.'),
    facts: localFacts(
      'Scan to PDF',
      'You get images in a PDF. Edges are not auto-cropped by a model in this beta, and there is no text layer.',
      'A dark photo stays hard to read. Retake it rather than expecting a server to enhance it.',
      'Read the PDF at the size you will send. If a corner is cut off, capture that page again.',
    ),
    related: ['jpg-to-pdf', 'compress-pdf', 'rotate-pdf', 'ocr-pdf', 'compress-image', 'organize-pdf'],
    guides: ['guides/turn-photos-into-a-pdf', 'guides/make-a-scanned-pdf-searchable', 'guides/compress-a-pdf-on-iphone'],
    intent: 'transactional',
    priority: 2,
    keywords: ['scan to pdf', 'camera to pdf'],
  },
  {
    path: 'pdf-forms',
    kind: 'tool',
    h1: 'PDF forms',
    keyword: 'pdf forms',
    description: 'Read what filling PDF forms requires, with no upload. This version will not pretend to complete an AcroForm.',
    toolId: 'forms',
    essay:
      'PDF forms store values in fields. Filling them means writing those values, not drawing text that a system cannot read. This version does not fill AcroForm fields, and it will not flatten a fake overlay and call the form complete. Many fill-online sites upload the form, including what you type. Use a local reader that supports fields until this app can write the values and show you what it wrote.',
    steps: how('PDF forms'),
    points: why('the form is not uploaded just because this page cannot fill the fields yet.'),
    facts: localFacts(
      'PDF forms',
      'Fields are not filled in this version. No overlay is flattened into a fake completed form.',
      'Typing on a screenshot is not filling the form. A portal that reads field values would see them empty.',
      'Open the form in a reader that shows fields. If you can type and save there, that reader did the job locally.',
    ),
    related: ['sign-pdf', 'edit-pdf', 'pdf-to-word', 'compress-pdf', 'merge-pdf', 'watermark-pdf'],
    guides: ['guides/sign-a-pdf-without-printing', 'guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'commercial',
    priority: 2,
    keywords: ['pdf forms', 'fill pdf form'],
  },
  {
    path: 'summarize-pdf',
    kind: 'tool',
    h1: 'Summarize PDF',
    keyword: 'summarize pdf',
    description: 'Summarize a PDF only with this browser’s on-device model. No upload, and no cloud fallback.',
    toolId: 'summarize',
    essay:
      'Summarize PDF uses the browser’s own on-device summarizer when one exists. If it does not, the button stays off. There is no fallback that sends the text to a hosted model. A summary can omit a number that matters, so read the source before you rely on it. A scan without a text layer will not be summarized into a story. The boundary is on-device or not at all.',
    steps: how('Summarize PDF'),
    points: why('there is no cloud model behind the button. Missing support means the tool stays disabled.'),
    facts: localFacts(
      'Summarize PDF',
      'You may get a short summary from a local model. It can skip details. The PDF itself is unchanged. If the browser cannot summarize, nothing happens.',
      'Do not skip reading the source, and do not expect a briefing from a scan that has no text layer.',
      'Compare any summary with the pages. If a date or a fee is missing, the summary is not the record.',
    ),
    related: ['translate-pdf', 'pdf-to-word', 'compare-pdf', 'ocr-pdf', 'compress-pdf', 'pdf-to-markdown'],
    guides: ['guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/is-it-safe-to-upload-pdfs', 'guides/make-a-scanned-pdf-searchable'],
    intent: 'commercial',
    priority: 3,
    keywords: ['summarize pdf', 'pdf summary'],
  },
  {
    path: 'translate-pdf',
    kind: 'tool',
    h1: 'Translate PDF',
    keyword: 'translate pdf',
    description: 'Translate PDF text only with this browser’s on-device translator. No upload and no cloud fallback.',
    toolId: 'translate',
    essay:
      'Translate PDF uses the browser’s on-device translator when it exists. If it does not, the control stays disabled. Text is not sent to a translation website. Translation can be wrong on names, dosages, and legal terms. Treat the result as a reading aid and keep the original. Scans without a text layer are not translated, and this version will not OCR them first in secret.',
    steps: how('Translate PDF'),
    points: why('translation either runs in the browser’s own model or it does not run.'),
    facts: localFacts(
      'Translate PDF',
      'You get a reading aid, not a certified translation. The original PDF is the record. A missing local translator means no translation.',
      'Do not act on a translated dose or a legal term without a person who can check it.',
      'Read the original beside the translation. If a name changed meaning, ignore the translation for that line.',
    ),
    related: ['summarize-pdf', 'pdf-to-word', 'pdf-to-markdown', 'ocr-pdf', 'compare-pdf', 'compress-pdf'],
    guides: ['guides/what-a-browser-pdf-tool-can-and-cannot-do', 'guides/pdf-to-word-what-you-keep', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'commercial',
    priority: 3,
    keywords: ['translate pdf', 'pdf translation'],
  },
  {
    path: 'pdf-workflows',
    kind: 'tool',
    h1: 'PDF workflows',
    keyword: 'pdf workflows',
    description: 'Run a saved on-device PDF workflow with no upload. The recipe rotates, watermarks, and numbers pages.',
    toolId: 'workflows',
    essay:
      'PDF workflows runs a short recipe on this device: rotate, then a Draft watermark, then page numbers. You can save the step list in local preferences. The preference is the list of steps, not the file. The file is not stored for later and not uploaded so a server can remember the workflow. Check the result, because a recipe can stamp Draft on a file you meant to send clean.',
    steps: how('PDF workflows'),
    points: why('the recipe runs in this tab, and only the step names are kept locally.'),
    facts: localFacts(
      'PDF workflows',
      'The built-in recipe rotates, stamps Draft, and adds page numbers. Saved workflows store step names, not the document.',
      'Do not save a workflow in place of reading the result. Draft on a final contract is your mistake to catch.',
      'Open the download. You should see the watermark and the numbers, and the pages should face the right way.',
    ),
    related: ['rotate-pdf', 'watermark-pdf', 'add-page-numbers-to-pdf', 'compress-pdf', 'merge-pdf', 'organize-pdf'],
    guides: ['guides/watermark-a-contract', 'guides/add-page-numbers', 'guides/organize-pages-before-you-send'],
    intent: 'transactional',
    priority: 3,
    keywords: ['pdf workflow', 'batch pdf'],
  },
];
