import { how, localFacts, why, type Seed } from './factory';
import { IMAGE_SIZE_SLUGS, PDF_SIZE_SLUGS } from '../src/seo/routes';

export const toolSeeds: Seed[] = [
  {
    path: 'compress-pdf',
    kind: 'tool',
    h1: 'Compress PDF',
    keyword: 'compress pdf',
    title: 'Compress PDF – Pick an Exact Size, Free | Weesize',
    description: 'Compress PDF to an exact KB or MB target. Free, unlimited, and 100% private: files stay on your device with no upload. Drop your PDF to shrink.',
    toolId: 'compress',
    essay:
      'Compress PDF when photos or scans inside the file are larger than needed for form uploads. Choose an exact KB target or reduction preset. Text remains crisp and selectable. All compression runs in memory on your device without uploading files to any server.',
    steps: how('Compress PDF'),
    points: why('the PDF is processed entirely on your device with zero cloud upload.'),
    facts: localFacts(
      'Compress PDF',
      'Images are optimized and downscaled as needed to hit the exact target size. Text remains crisp and searchable.',
      'If the PDF is already well-compressed, the tool informs you honestly instead of degrading quality.',
      'Check the downloaded file to ensure it meets your form upload limit.',
    ),
    related: ['compress-image', 'merge-pdf', 'split-pdf', 'signature-resizer', 'id-photo', 'pdf-to-jpg'],
    neighbors: PDF_SIZE_SLUGS,
    guides: ['guides/why-is-my-pdf-so-large', 'guides/reduce-pdf-size-without-losing-quality', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor', 'compress pdf to exact size', 'compress pdf to 100kb', 'compress pdf to 200kb'],
  },
  {
    path: 'compress-image',
    kind: 'tool',
    h1: 'Compress Image',
    keyword: 'compress image',
    title: 'Compress Image – Exact KB Size for Forms | Weesize',
    description: 'Compress JPG, PNG, WebP, and HEIC photos to an exact KB target. Free, fast, and 100% private: processed in your browser with zero uploads.',
    toolId: 'compress-images',
    essay:
      'Compress photos and scans to the exact KB file size required by government, visa, and exam portals. Supports JPG, PNG, WebP, and iPhone HEIC photos. Strips camera and location metadata by default while preserving image sharpness.',
    steps: how('Compress image'),
    points: why('images are resized and compressed on your device without any server upload.'),
    facts: localFacts(
      'Compress Image',
      'Select any target from 10 KB to 500 KB or enter a custom limit. The output is always at or below your target.',
      'GPS location tags and camera metadata are stripped automatically for privacy.',
      'If an image cannot reach the target size while remaining readable, the tool explains the exact minimum possible size.',
    ),
    related: ['signature-resizer', 'id-photo', 'compress-pdf', 'jpg-to-pdf', 'check-pdf-before-sending'],
    neighbors: IMAGE_SIZE_SLUGS,
    guides: ['guides/reduce-pdf-size-without-losing-quality', 'guides/why-is-my-pdf-so-large'],
    intent: 'transactional',
    priority: 1,
    keywords: ['compress image', 'compress image to 20kb', 'compress image to 50kb', 'compress image to 100kb', 'reduce photo size in kb', 'resize image for form'],
  },
  {
    path: 'signature-resizer',
    kind: 'tool',
    h1: 'Signature Resizer',
    keyword: 'resize signature',
    title: 'Signature Resizer – Clean Background & Exact KB | Weesize',
    description: 'Resize signature photo for forms: clean background to white, darken ink, and hit exact KB and pixel targets. Free, on-device with no upload.',
    toolId: 'signature-resizer',
    essay:
      'Resize photographed or scanned signatures to the exact dimensions and KB limits required by online applications (JEE, NEET, UPSC, SSC, passport, and job portals). Cleans gray paper backgrounds to pure white, darkens pen strokes, and crops tightly around the ink.',
    steps: how('Signature resizer'),
    points: why('your signature photo is enhanced and resized locally on your device without leaving your browser.'),
    facts: localFacts(
      'Signature Resizer',
      'Auto-crops margins, removes paper shadows, and enhances contrast for clean form submission.',
      'Choose exact pixel dimensions (e.g. 140×60 px) and file size limits (e.g. 10–20 KB).',
      'Download as JPG or PNG ready for instant upload to any portal.',
    ),
    related: ['compress-image', 'id-photo', 'compress-pdf', 'get-it-accepted'],
    guides: ['guides/organize-pages-before-you-send', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['signature resizer', 'resize signature', 'signature photo resize 20kb', 'signature photo resize 50kb', 'darken signature online', 'jee signature resize'],
  },
  {
    path: 'id-photo',
    kind: 'tool',
    h1: 'ID & Passport Photo Maker',
    keyword: 'passport photo maker',
    title: 'ID & Passport Photo Maker – Exact Dimensions | Weesize',
    description: 'Crop passport and visa photos to exact mm, inch, or pixel sizes with plain background. Free, private, and 100% on-device.',
    toolId: 'id-photo',
    essay:
      'Crop portrait photos to official passport, visa, and ID requirements (US 2×2 in, UK/Schengen 35×45 mm, India, Canada). Change background color to compliant white or off-white. The face is never retouched or distorted.',
    steps: how('ID photo'),
    points: why('your photo is framed and formatted in your browser with zero data sent to external servers.'),
    facts: localFacts(
      'ID Photo Maker',
      'Supports standard passport presets (2×2 inch, 35×45 mm, 33×48 mm) or custom pixel/mm inputs at 300 DPI.',
      'Creates printable 4×6 inch photo sheets with multiple passport photos ready to print.',
      'Face proportion and centering are maintained without artificial AI alterations.',
    ),
    related: ['compress-image', 'signature-resizer', 'compress-pdf', 'get-it-accepted'],
    guides: ['guides/organize-pages-before-you-send', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['passport photo maker', 'id photo maker', 'passport size photo 2x2', 'visa photo resize', 'passport photo 35x45 mm'],
  },
  {
    path: 'get-it-accepted',
    kind: 'tool',
    h1: 'Get It Accepted (Presets & Custom Rule)',
    keyword: 'form upload requirements checker',
    title: 'Get It Accepted – Check Files Against Form Rules | Weesize',
    description: 'Verify your photo, signature, or PDF against official upload rules or type any custom form rule. Free and 100% private.',
    toolId: 'presets',
    essay:
      'Check whether your file meets exact official specifications before submitting it to government portals, exam boards, or visa applications. Or type any custom requirement (e.g. "JPG, 20–50 KB, 200×230 px") and get an instant checklist.',
    steps: how('Get it accepted'),
    points: why('verification runs locally in your browser against verified specifications.'),
    facts: localFacts(
      'Get It Accepted',
      'Includes verified presets for major exams and passport services with source links and check dates.',
      'Type any custom rule string and Weesize parses file format, size limits, and pixel bounds automatically.',
      'Shows a clear pass/fail checklist detailing file size, dimensions, and format.',
    ),
    related: ['compress-image', 'signature-resizer', 'id-photo', 'compress-pdf'],
    guides: ['guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['form upload checker', 'file size checker for forms', 'passport photo requirements', 'jee form upload rule'],
  },
  {
    path: 'merge-pdf',
    kind: 'tool',
    h1: 'Merge PDF',
    keyword: 'merge pdf',
    title: 'Merge PDF – Combine Files Free, No Upload | Weesize',
    description: 'Combine multiple PDFs into one document in seconds. Free, unlimited, and 100% private with no upload or sign-up. Drop your files to merge now.',
    toolId: 'merge',
    essay:
      'Combine cover letters, supporting documents, certificates, and scans into a single organized PDF. Drag and drop to order files exactly as desired. Built entirely on your device with no upload caps.',
    steps: how('Merge PDF'),
    points: why('every source PDF stays on this device while the pages are combined into one file.'),
    facts: localFacts(
      'Merge PDF',
      'Pages are merged in the exact order shown on screen.',
      'Combine unlimited PDFs without waiting for cloud queues.',
      'Download your merged PDF immediately with zero server latency.',
    ),
    related: ['compress-pdf', 'organize-pdf', 'split-pdf', 'jpg-to-pdf', 'add-page-numbers-to-pdf', 'watermark-pdf'],
    guides: ['guides/merge-pdfs-without-an-account', 'guides/organize-pages-before-you-send', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['merge pdf', 'combine pdf', 'join pdf files'],
  },
  {
    path: 'split-pdf',
    kind: 'tool',
    h1: 'Split PDF',
    keyword: 'split pdf',
    title: 'Split PDF – Extract Pages Free, No Upload | Weesize',
    description: 'Extract pages or page ranges from any PDF instantly. Free, unlimited, and 100% private with no upload or sign-up. Select your PDF to split.',
    toolId: 'split',
    essay:
      'Extract specific pages or custom page ranges (e.g. 1-3, 5, 8-10) from large documents. Perfect for isolating single statements, certificates, or chapters.',
    steps: how('Split PDF'),
    points: why('only the pages you keep are written, and the source never leaves this device.'),
    facts: localFacts(
      'Split PDF',
      'Extract individual pages or multiple page ranges in one step.',
      'Original formatting, embedded text, and vector graphics are preserved perfectly.',
      'No data leaves your device during page extraction.',
    ),
    related: ['merge-pdf', 'organize-pdf', 'compress-pdf', 'rotate-pdf', 'pdf-to-jpg', 'repair-pdf'],
    guides: ['guides/split-a-pdf-by-page-range', 'guides/organize-pages-before-you-send', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['split pdf', 'extract pdf pages', 'separate pdf'],
  },
  {
    path: 'organize-pdf',
    kind: 'tool',
    h1: 'Organize PDF',
    keyword: 'organize pdf',
    title: 'Organize PDF – Reorder & Rotate Pages Free | Weesize',
    description: 'Reorder, rotate, and delete PDF pages right in your browser. Free, unlimited, and 100% private with no upload. Arrange your document now.',
    toolId: 'organize',
    essay:
      'Rearrange pages, rotate upside-down scans, and delete unwanted blank pages visually using an interactive grid thumbnail viewer.',
    steps: how('Organize PDF'),
    points: why('thumbnails are rendered locally, so organizing sensitive files requires no account or cloud transfer.'),
    facts: localFacts(
      'Organize PDF',
      'Drag and drop page thumbnails to reorder.',
      'Rotate single pages or bulk-delete blank and accidental scan pages.',
      'Saved file reflects your exact layout changes.',
    ),
    related: ['merge-pdf', 'split-pdf', 'rotate-pdf', 'compress-pdf', 'add-page-numbers-to-pdf', 'crop-pdf'],
    guides: ['guides/organize-pages-before-you-send', 'guides/merge-pdfs-without-an-account', 'guides/split-a-pdf-by-page-range'],
    intent: 'transactional',
    priority: 1,
    keywords: ['organize pdf', 'reorder pdf pages', 'delete pdf pages', 'rearrange pdf'],
  },
  {
    path: 'rotate-pdf',
    kind: 'tool',
    h1: 'Rotate PDF',
    keyword: 'rotate pdf',
    title: 'Rotate PDF – Turn Pages 90° or 180° Free | Weesize',
    description: 'Permanently rotate PDF pages clockwise, counter-clockwise, or upside down. Free, private, and fast in your browser.',
    toolId: 'rotate',
    essay:
      'Fix sideways scans and landscape pages permanently. Rotates pages by 90, 180, or 270 degrees in the underlying PDF page dictionary so every PDF reader displays them correctly.',
    steps: how('Rotate PDF'),
    points: why('rotation metadata is updated on your device without re-compressing or uploading.'),
    facts: localFacts(
      'Rotate PDF',
      'Applies clean 90-degree rotations across all pages.',
      'Changes are saved permanently in standard PDF rotation attributes.',
      'Fast and lossless: image bytes are not re-compressed.',
    ),
    related: ['organize-pdf', 'crop-pdf', 'compress-pdf', 'merge-pdf'],
    guides: ['guides/organize-pages-before-you-send'],
    intent: 'transactional',
    priority: 1,
    keywords: ['rotate pdf', 'turn pdf pages', 'rotate pdf permanently'],
  },
  {
    path: 'crop-pdf',
    kind: 'tool',
    h1: 'Crop PDF',
    keyword: 'crop pdf',
    title: 'Crop PDF – Trim Margins on All Pages | Weesize',
    description: 'Trim margins and extra white space from PDF pages. Free, fast, and 100% private in your browser.',
    toolId: 'crop',
    essay:
      'Trim margins and white space from PDF pages evenly. Sets the CropBox and MediaBox parameters to focus on the document content.',
    steps: how('Crop PDF'),
    points: why('margin adjustments happen locally in memory.'),
    facts: localFacts(
      'Crop PDF',
      'Set exact point margins to trim scanner borders and printer marks.',
      'Applied cleanly across all document pages.',
      'Preserves original vector text and image sharpness.',
    ),
    related: ['rotate-pdf', 'organize-pdf', 'compress-pdf'],
    guides: ['guides/organize-pages-before-you-send'],
    intent: 'transactional',
    priority: 1,
    keywords: ['crop pdf', 'trim pdf margins', 'cut pdf margins'],
  },
  {
    path: 'jpg-to-pdf',
    kind: 'tool',
    h1: 'Images to PDF',
    keyword: 'jpg to pdf',
    title: 'Images to PDF – Convert Photos to PDF Free | Weesize',
    description: 'Convert JPG, PNG, and WebP images into a clean PDF document. Free, unlimited, and 100% private with no upload.',
    toolId: 'images',
    essay:
      'Convert phone photos, scanned documents, receipts, and screenshots into a single multi-page PDF. Choose page size (A4, Letter, or Fit to Image) and margin settings.',
    steps: how('Images to PDF'),
    points: why('your pictures are embedded directly into a PDF on your device.'),
    facts: localFacts(
      'Images to PDF',
      'Drop multiple JPG, PNG, and WebP photos to generate a multi-page PDF.',
      'Supports auto-orientation and standard A4 or Letter page sizing.',
      'Fast, offline-ready conversion with zero file limits.',
    ),
    related: ['pdf-to-jpg', 'compress-pdf', 'compress-image', 'merge-pdf'],
    guides: ['guides/shrink-photos-for-applications', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['jpg to pdf', 'images to pdf', 'photos to pdf', 'png to pdf'],
  },
  {
    path: 'pdf-to-jpg',
    kind: 'tool',
    h1: 'PDF to Images',
    keyword: 'pdf to jpg',
    title: 'PDF to JPG – Extract Pages as Images Free | Weesize',
    description: 'Convert PDF pages into high-resolution JPG images. Download single images or a ZIP file. Free and private.',
    toolId: 'pdf-images',
    essay:
      'Convert each page of a PDF document into a crisp JPEG image. Download individual page images or all pages in a convenient ZIP archive.',
    steps: how('PDF to images'),
    points: why('rendering uses in-browser WebAssembly with zero server interaction.'),
    facts: localFacts(
      'PDF to Images',
      'Renders high-resolution JPEGs suitable for sharing and embedding.',
      'Single-page PDFs download directly as a JPG; multi-page PDFs download as a ZIP.',
      'Private: pages are rendered into local canvas buffers only.',
    ),
    related: ['jpg-to-pdf', 'compress-pdf', 'compress-image'],
    guides: ['guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['pdf to jpg', 'pdf to image', 'convert pdf to jpeg', 'extract images from pdf'],
  },
  {
    path: 'add-page-numbers-to-pdf',
    kind: 'tool',
    h1: 'Page Numbers',
    keyword: 'add page numbers to pdf',
    title: 'Add Page Numbers to PDF – Free, No Upload | Weesize',
    description: 'Add page numbers to the header or footer of any PDF. Custom start numbers and cover page skip. Free, 100% on-device.',
    toolId: 'numbers',
    essay:
      'Number PDF pages clearly for reports, court filings, manuscripts, and contracts. Set starting page number and choose whether to skip numbering the cover page.',
    steps: how('Page numbers'),
    points: why('numbers are drawn into the PDF streams locally on your device.'),
    facts: localFacts(
      'Page Numbers',
      'Number all pages sequentially in the bottom footer.',
      'Optionally skip numbering on the first/cover page.',
      'Embeds clean standard font numbering into the document.',
    ),
    related: ['watermark-pdf', 'organize-pdf', 'merge-pdf', 'compress-pdf'],
    guides: ['guides/organize-pages-before-you-send'],
    intent: 'transactional',
    priority: 1,
    keywords: ['add page numbers to pdf', 'number pdf pages', 'paginate pdf'],
  },
  {
    path: 'watermark-pdf',
    kind: 'tool',
    h1: 'Watermark PDF',
    keyword: 'watermark pdf',
    title: 'Watermark PDF – Stamp Text Across Pages Free | Weesize',
    description: 'Add a custom text watermark (e.g. DRAFT, CONFIDENTIAL) across all PDF pages. Free and private in your browser.',
    toolId: 'watermark',
    essay:
      'Stamp text watermarks like "DRAFT", "CONFIDENTIAL", or your company name across every page of a PDF with clean opacity.',
    steps: how('Watermark'),
    points: why('watermark stamps are embedded directly in the PDF streams on your device.'),
    facts: localFacts(
      'Watermark PDF',
      'Custom text stamp positioned across all pages.',
      'Semi-transparent styling ensures underlying text remains legible.',
      'Ideal for review copies, NDA drafts, and sample distributions.',
    ),
    related: ['add-page-numbers-to-pdf', 'organize-pdf', 'compress-pdf'],
    guides: ['guides/organize-pages-before-you-send'],
    intent: 'transactional',
    priority: 1,
    keywords: ['watermark pdf', 'add watermark to pdf', 'draft stamp pdf'],
  },
  {
    path: 'repair-pdf',
    kind: 'tool',
    h1: 'Repair PDF',
    keyword: 'repair pdf',
    title: 'Repair PDF – Rebuild Damaged Files Free | Weesize',
    description: 'Fix corrupt or unreadable PDF files by rebuilding the cross-reference table and structure. Free and 100% private.',
    toolId: 'repair',
    essay:
      'Repair broken or damaged PDF files by recovering streams and rebuilding corrupt cross-reference tables so the document can be opened and printed normally.',
    steps: how('Repair PDF'),
    points: why('recovery runs on your device so damaged confidential files remain private.'),
    facts: localFacts(
      'Repair PDF',
      'Scans damaged byte streams and reconstructs missing xref tables.',
      'Restores unreadable PDFs produced by crashed exports or incomplete downloads.',
      'Processes files locally with zero upload.',
    ),
    related: ['compress-pdf', 'organize-pdf', 'split-pdf'],
    guides: ['guides/why-is-my-pdf-so-large', 'guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['repair pdf', 'fix corrupt pdf', 'recover damaged pdf'],
  },
  {
    path: 'check-pdf-before-sending',
    kind: 'tool',
    h1: 'Safe to Share (Sanitize)',
    keyword: 'remove metadata from pdf',
    title: 'Safe to Share – Remove PDF & Photo Metadata | Weesize',
    description: 'Inspect and sanitize PDFs and photos before sending. Free tool removes GPS coordinates, author metadata, and edit history.',
    toolId: 'share-check',
    essay:
      'Inspect and clean hidden metadata from PDF documents and photos before emailing or uploading them. Strips camera models, GPS locations, author names, software titles, and hidden form metadata.',
    steps: how('Safe to share'),
    points: why('metadata inspection and stripping run entirely on your device.'),
    facts: localFacts(
      'Safe to Share',
      'Detects GPS tags in phone photos and strips location data completely.',
      'Cleans PDF creation metadata, author names, and modified date records.',
      'Ensures private files do not leak sensitive personal or location information.',
    ),
    related: ['compress-pdf', 'compress-image', 'repair-pdf'],
    guides: ['guides/is-it-safe-to-upload-pdfs'],
    intent: 'transactional',
    priority: 1,
    keywords: ['remove metadata from pdf', 'sanitize pdf', 'strip exif from photo', 'remove gps from image', 'pdf privacy check'],
  },
];
